/**
 * فهرس المقالات الخفيف (Metadata فقط)
 * =====================================
 *
 * ⚡ لماذا هذا الملف منفصل عن محتوى المقالات؟
 *
 * المعمارية السابقة كانت تستورد كل المقالات استاتيكياً في registry.ts.
 * مع 10 مقالات كان الحمل مقبولاً، لكن مع 90 مقالاً (الهدف) فإن أي صفحة
 * تعرض قائمة — /blog، sitemap، الروابط ذات الصلة — كانت ستُحمّل
 * ~500 KB من نصوص المقالات في الذاكرة لتعرض عناوين فقط.
 *
 * الحل: فصل الطبقتين
 *   • هذا الملف: بيانات خفيفة (عنوان، تاريخ، تصنيف) — بضعة كيلوبايتات
 *   • posts/*.ts: المحتوى الكامل — يُحمَّل ديناميكياً لمقال واحد فقط
 *
 * ⚠️ هذا الملف **مولَّد آلياً**. لا تعدّله يدوياً.
 *    شغّل: node scripts/generate-article-meta.mjs
 */

import type { ArticleCategory, ArticleIntent } from "./types";

export interface ArticleMeta {
    slug: string;
    title: string;
    seoTitle?: string;
    excerpt: string;
    category: ArticleCategory;
    intent: ArticleIntent;
    publishAt: string;
    dateModified: string;
    author: string;
    authorRole?: string;
    image: string;
    imageAlt: string;
    readTime: string;
    /** الكلمة المفتاحية الرئيسية — تُستخدم في الروابط ذات الصلة */
    primaryKeyword: string;
}

/* ⬇️ AUTO-GENERATED — start */
export const ARTICLE_META: ArticleMeta[] = [
    {
        slug: "year-end-print-planning",
        title: "تجهيزات نهاية السنة المالية: الأجندات والتقارير",
        seoTitle: "أجندات نهاية السنة والتقارير السنوية",
        excerpt: "خطة عملية لموسم نهاية السنة المالية: متى تطلب الأجندات والتقاويم، كيف تجهّز التقرير السنوي، وما المطبوعات الإدارية التي تتجدد مع بداية السنة — مع جداول توقيت ونطاقات أسعار استرشادية.",
        category: "موسمي",
        intent: "commercial",
        publishAt: "2026-11-19T17:09:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم الطباعة التجارية والهدايا المؤسسية",
        image: "/images/branded-notebooks-diaries-calendar-gift-sets.webp",
        imageAlt: "أجندات ودفاتر وتقويم مكتبي مطبوعة بشعار الشركة ضمن طقم هدايا نهاية السنة داخل مطبعة في جدة",
        readTime: "14 دقيقة",
        primaryKeyword: "أجندات نهاية السنة",
    },
    {
        slug: "national-day-printing",
        title: "مطبوعات وهدايا اليوم الوطني السعودي",
        seoTitle: "مطبوعات وهدايا اليوم الوطني: دليل التجهيز",
        excerpt: "دليل تنفيذي لتجهيز حملة اليوم الوطني: جدول زمني لكل بند، خامات الواجهات في مناخ جدة، ضبط اللون الأخضر، نطاقات أسعار استرشادية.\nمع قواعد استخدام العلم والهوية الوطنية، وخطة الإزالة والتخزين بعد 23 سبتمبر.",
        category: "موسمي",
        intent: "commercial",
        publishAt: "2026-11-17T12:22:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم الحملات الموسمية والهدايا الدعائية",
        image: "/images/custom-printed-metal-plastic-pens.webp",
        imageAlt: "أقلام معدنية وبلاستيكية مطبوعة بالشعار ضمن تجهيزات اليوم الوطني داخل مطبعة في جدة",
        readTime: "12 دقيقة",
        primaryKeyword: "مطبوعات اليوم الوطني",
    },
    {
        slug: "ramadan-corporate-gifts",
        title: "هدايا رمضان للشركات: دليل الاختيار والتوقيت",
        seoTitle: "هدايا رمضان للشركات: الاختيار والتوقيت",
        excerpt: "دليل تشغيلي لهدايا رمضان للشركات: جدول زمني يبدأ قبل 12 أسبوعاً، أصناف تنجح فعلاً، نطاقات ميزانية حسب مستوى المستلم، وتقنية تنفيذ الشعار على كل خامة.\nمع بنود التغليف والمواد الغذائية ولوجستيات التسليم داخل جدة خلال الشهر.",
        category: "موسمي",
        intent: "commercial",
        publishAt: "2026-11-14T09:42:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم الهدايا الدعائية والمناسبات",
        image: "/images/corporate-promotional-gifts-jeddah-items.webp",
        imageAlt: "مجموعة هدايا رمضانية للشركات مع علب تمور ومستلزمات ضيافة جاهزة للتغليف داخل مطبعة في حي الروضة بجدة",
        readTime: "12 دقيقة",
        primaryKeyword: "هدايا رمضان للشركات",
    },
    {
        slug: "education-printing",
        title: "مطبوعات المدارس والمراكز التعليمية",
        seoTitle: "مطبوعات المدارس: الخامات والتوقيت",
        excerpt: "ما تحتاجه المدرسة أو المركز التعليمي من مطبوعات، بأي خامة ووزن ورق، ومتى تطلب كل صنف قبل بداية العام الدراسي — مع نطاقات أسعار استرشادية.",
        category: "مطبوعات",
        intent: "commercial",
        publishAt: "2026-11-12T11:53:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المطبوعات التجارية والمؤسسية",
        image: "/images/branded-notebooks-diaries-calendar-gift-sets.webp",
        imageAlt: "دفاتر ومفكرات وتقويم بشعار مؤسسة تعليمية ضمن مجموعة مطبوعات معدّة في جدة",
        readTime: "13 دقيقة",
        primaryKeyword: "مطبوعات المدارس",
    },
    {
        slug: "real-estate-printing",
        title: "مطبوعات شركات العقار: أدوات البيع الورقية",
        seoTitle: "مطبوعات شركات العقار: الدليل العملي",
        excerpt: "ما الذي تحتاجه شركة العقار فعلاً من مطبوعات: ملف العرض، ورقة الوحدة، كتيّب المشروع، لوحات الموقع، ودفاتر الحجز — بمواصفات وكميات ونطاقات أسعار للسوق السعودي.",
        category: "مطبوعات",
        intent: "commercial",
        publishAt: "2026-11-10T08:04:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المطبوعات التجارية",
        image: "/images/presentation-folder-files-holder.webp",
        imageAlt: "ملف عرض تقديمي لشركة عقارية مع أوراق الوحدات السكنية داخل مطبعة في جدة",
        readTime: "14 دقيقة",
        primaryKeyword: "مطبوعات شركات العقار",
    },
    {
        slug: "cafe-restaurant-printing",
        title: "مطبوعات المقاهي والمطاعم: من المنيو حتى التغليف",
        seoTitle: "مطبوعات المقاهي والمطاعم: من المنيو للتغليف",
        excerpt: "خريطة كاملة لمطبوعات المقهى والمطعم: المنيو، الأكواب، علب السفري، الملصقات، الفواتير، اللافتات، وزي الطاقم — مع الخامات المناسبة لمناخ جدة ونطاقات أسعار استرشادية.",
        category: "مطبوعات",
        intent: "commercial",
        publishAt: "2026-11-08T11:18:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المطبوعات التجارية والتغليف",
        image: "/images/restaurant-menu-design-leather-cover.webp",
        imageAlt: "منيو مطعم بغلاف جلدي ضمن حزمة مطبوعات مقهى ومطعم منفّذة في جدة",
        readTime: "13 دقيقة",
        primaryKeyword: "مطبوعات المقاهي والمطاعم",
    },
    {
        slug: "medical-clinic-printing",
        title: "مطبوعات العيادات والمراكز الطبية: الدليل الكامل",
        seoTitle: "مطبوعات العيادات والمراكز الطبية: دليل كامل",
        excerpt: "كل مطبوعة تحتاجها العيادة من دفتر الوصفات حتى لافتة غرفة الكشف: المقاسات والخامات والجرامات والكميات الاقتصادية. مع ما يخصّ رطوبة جدة وبروتوكولات التعقيم ونطاقات أسعار استرشادية.",
        category: "مطبوعات",
        intent: "commercial",
        publishAt: "2026-11-05T08:09:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المطبوعات التجارية والمؤسسية",
        image: "/images/corporate-letterhead-envelope-branding.webp",
        imageAlt: "أوراق رسمية وظروف بهوية بصرية موحّدة لمركز طبي في جدة",
        readTime: "12 دقيقة",
        primaryKeyword: "مطبوعات العيادات الطبية",
    },
    {
        slug: "print-finishes-guide",
        title: "دليل تشطيبات الطباعة: من السلوفان إلى الختم الحراري",
        seoTitle: "دليل تشطيبات الطباعة: سلوفان وUV وختم حراري",
        excerpt: "مرجع تقني لكل تشطيب متاح في السوق السعودي — السلوفان بأنواعه، الـUV الموضعي، الختم الحراري، البارز والغائر، القص الخاص وتلوين الحواف.\nمتى يستحق كل تشطيب تكلفته، وكيف تُجهّز ملفك حتى يُنفَّذ صحيحاً من أول مرة.",
        category: "مرجعي",
        intent: "reference",
        publishAt: "2026-11-03T10:58:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم ما بعد الطباعة والتشطيبات",
        image: "/images/luxury-business-cards-printing-jeddah.webp",
        imageAlt: "بطاقات عمل بتشطيبات ختم حراري ذهبي وسبوت UV وسلوفان مخملي منفّذة في مطبعة بجدة",
        readTime: "12 دقيقة",
        primaryKeyword: "تشطيبات الطباعة",
    },
    {
        slug: "exhibition-stands-sizes",
        title: "مقاسات ستاندات ومعدات المعارض القياسية",
        seoTitle: "مقاسات ستاندات المعارض: دليل مرجعي",
        excerpt: "مرجع كامل لمقاسات الرول أب والبوب أب والكاونترات وأجنحة الأوكتانورم في السوق السعودي، مع مقاس الطباعة الحقيقي ومنطقة الأمان والدقة المطلوبة لكل نوع.",
        category: "مرجعي",
        intent: "reference",
        publishAt: "2026-11-01T15:22:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المعارض والفعاليات",
        image: "/images/roll-up-stand-banner-85x200.webp",
        imageAlt: "ستاند رول أب بمقاس 85×200 سم جاهز للعرض ضمن تجهيزات معرض في جدة",
        readTime: "12 دقيقة",
        primaryKeyword: "مقاسات ستاندات المعارض",
    },
    {
        slug: "pantone-colors-guide",
        title: "دليل ألوان Pantone: متى تحتاجها وكيف تختارها",
        seoTitle: "متى تحتاج ألوان Pantone وكيف تختارها",
        excerpt: "متى يستحق اللون الفوري Pantone تكلفته الإضافية، وكيف تقرأ أكواده، ولماذا يتغيّر لون علامتك بين الورق واللافتة والتيشيرت — بمعايير عملية للسوق السعودي.",
        category: "مرجعي",
        intent: "reference",
        publishAt: "2026-10-29T11:13:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم التجهيز قبل الطباعة وإدارة الألوان",
        image: "/images/printing-machines-digital-offset-equipment.webp",
        imageAlt: "ماكينات طباعة أوفست ورقمية داخل مطبعة في جدة أثناء ضبط الألوان ومطابقتها",
        readTime: "12 دقيقة",
        primaryKeyword: "دليل ألوان Pantone",
    },
    {
        slug: "printing-glossary-arabic",
        title: "معجم مصطلحات الطباعة عربي-إنجليزي",
        seoTitle: "معجم مصطلحات الطباعة عربي-إنجليزي",
        excerpt: "مرجع يفكّ شفرة أكثر من 100 مصطلح تسمعه في المطابع ومحلات الدعاية بجدة، من الجرام والسي إم واي كيه إلى السلوفان واللامينيشن والأوكتانورم.",
        category: "مرجعي",
        intent: "reference",
        publishAt: "2026-10-27T10:47:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم ما قبل الطباعة",
        image: "/images/printing-machines-digital-offset-equipment.webp",
        imageAlt: "ماكينات طباعة أوفست ورقمية داخل مطبعة في جدة مع مصطلحات التشغيل الفنية",
        readTime: "13 دقيقة",
        primaryKeyword: "مصطلحات الطباعة",
    },
    {
        slug: "signage-materials-reference",
        title: "دليل خامات اللافتات الشامل: الخصائص والاستخدامات",
        seoTitle: "دليل خامات اللافتات: الخصائص والاستخدامات",
        excerpt: "مرجع تقني لكل خامة تصادفها في عروض لافتات جدة: اللدائن والمعادن والمركّبات والخامات السطحية، بسماكاتها ومقاساتها القياسية وسلوكها تحت الشمس والرطوبة المالحة، مع معجم مصطلحات ونطاقات تكلفة استرشادية.",
        category: "مرجعي",
        intent: "reference",
        publishAt: "2026-10-24T09:36:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم اللافتات والواجهات",
        image: "/images/3d-shop-signage-letters-acrylic-jeddah.webp",
        imageAlt: "حروف بارزة من الأكريليك على خلفية ألمنيوم مركّب في واجهة محل بجدة",
        readTime: "16 دقيقة",
        primaryKeyword: "دليل خامات اللافتات",
    },
    {
        slug: "print-campaign-planning",
        title: "كيف تخطّط لحملة مطبوعات متكاملة؟",
        seoTitle: "دليل تخطيط حملة مطبوعات متكاملة",
        excerpt: "منهجية عملية بست خطوات لبناء حملة مطبوعات مترابطة: تحديد الهدف، خريطة نقاط الاتصال، حساب الكميات، توزيع الميزانية، الجدول الزمني العكسي، وقياس النتيجة.",
        category: "أدلة إرشادية",
        intent: "informational",
        publishAt: "2026-10-22T17:58:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم إدارة المشاريع",
        image: "/images/print-shop-exhibition-services-saudi-arabia.webp",
        imageAlt: "مطبوعات دعائية متكاملة لحملة تسويقية واحدة معروضة داخل مطبعة في جدة",
        readTime: "13 دقيقة",
        primaryKeyword: "تخطيط حملة مطبوعات",
    },
    {
        slug: "signage-maintenance-guide",
        title: "كيف تحافظ على لافتة محلك في مناخ جدة؟",
        seoTitle: "صيانة لافتات المحلات في مناخ جدة: دليل عملي",
        excerpt: "دليل عملي لصيانة لافتة محلك تحت شمس جدة ورطوبتها المالحة: جدول فحص وتنظيف بالدورية الصحيحة، مواد التنظيف المسموحة والممنوعة لكل خامة، أعطال الإنارة الشائعة وأسبابها. مع نطاقات تكلفة استرشادية للصيانة، وعلامات تقول إن الاستبدال صار أوفر من الإصلاح.",
        category: "أدلة إرشادية",
        intent: "informational",
        publishAt: "2026-10-19T10:13:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم اللافتات والواجهات",
        image: "/images/3d-shop-signage-letters-acrylic-jeddah.webp",
        imageAlt: "حروف أكريليك بارزة مضاءة على واجهة محل في جدة تظهر حالة الإنارة والخلفية بعد الصيانة",
        readTime: "13 دقيقة",
        primaryKeyword: "صيانة لافتات المحلات",
    },
    {
        slug: "write-design-brief",
        title: "كيف تكتب بريف تصميم يوفّر عليك الوقت والمال؟",
        seoTitle: "كيف تكتب بريف تصميم احترافي",
        excerpt: "الوثيقة التي تختصر جولات التعديل وتمنع الجدل مع المصمم: عناصرها العشرة، نموذج جاهز للنسخ، وقائمة تحقق قبل الإرسال.",
        category: "أدلة إرشادية",
        intent: "informational",
        publishAt: "2026-10-16T11:53:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم التصميم والهوية البصرية",
        image: "/images/client-meeting-office-al-rawaj-jeddah.webp",
        imageAlt: "اجتماع بين عميل وفريق التصميم لمناقشة بريف مشروع في مكتب بجدة",
        readTime: "12 دقيقة",
        primaryKeyword: "كيف تكتب بريف تصميم",
    },
    {
        slug: "vehicle-wrap-design-guide",
        title: "كيف تجهّز تصميم تغليف السيارة؟ دليل المصمم",
        seoTitle: "دليل تصميم تغليف السيارات للمصممين",
        excerpt: "من قالب المركبة إلى ملف الطباعة النهائي: المقاييس والدقة والألوان والمناطق الممنوعة وأحجام الخطوط في تصميم تغليف السيارات.",
        category: "أدلة إرشادية",
        intent: "informational",
        publishAt: "2026-10-14T08:27:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم التصميم وبراندينج المركبات",
        image: "/images/commercial-vehicle-branding-car-wrapping-jeddah.webp",
        imageAlt: "سيارة تجارية مغلّفة بالفينيل بتصميم هوية واضح على الجانب في جدة",
        readTime: "12 دقيقة",
        primaryKeyword: "تصميم تغليف السيارات",
    },
    {
        slug: "gift-selection-by-occasion",
        title: "كيف تختار الهدية الدعائية المناسبة لكل مناسبة؟",
        seoTitle: "اختيار الهدية الدعائية حسب المناسبة",
        excerpt: "دليل عملي لاختيار الهدية الدعائية حسب المناسبة: رمضان، يوم التأسيس، اليوم الوطني، الافتتاحات، المعارض، نهاية السنة المالية، وتكريم الموظفين.\nمع جدول توقيت الطلب، نطاقات ميزانية استرشادية، وما يفسد الهدية في مناخ جدة.",
        category: "أدلة إرشادية",
        intent: "informational",
        publishAt: "2026-10-12T13:27:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم الهدايا الدعائية والمناسبات",
        image: "/images/corporate-promotional-gifts-jeddah-items.webp",
        imageAlt: "تشكيلة هدايا دعائية للشركات معدّة لمناسبات مختلفة داخل مطبعة في جدة",
        readTime: "11 دقيقة",
        primaryKeyword: "اختيار الهدية الدعائية للمناسبات",
    },
    {
        slug: "design-business-card-guide",
        title: "كيف تصمّم بطاقة عمل احترافية؟ دليل عملي",
        seoTitle: "كيف تصمم بطاقة عمل احترافية: دليل عملي",
        excerpt: "خطوات تصميم بطاقة العمل من المقاس وحد النزيف حتى الخطوط والألوان والورق والتشطيبات، مع قائمة تحقق قبل إرسال الملف للمطبعة.",
        category: "أدلة إرشادية",
        intent: "informational",
        publishAt: "2026-10-09T08:18:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم التصميم والتجهيز الطباعي",
        image: "/images/luxury-business-cards-printing-jeddah.webp",
        imageAlt: "بطاقات عمل فاخرة بتشطيبات متعددة معروضة داخل مطبعة في جدة",
        readTime: "12 دقيقة",
        primaryKeyword: "كيف تصمم بطاقة عمل احترافية",
    },
    {
        slug: "kraft-vs-coated-packaging",
        title: "ورق كرافت أم كوشيه للتغليف؟ دليل اختيار خامة الأكياس",
        seoTitle: "ورق كرافت أم كوشيه للتغليف؟ دليل الاختيار",
        excerpt: "مقارنة عملية بين ورق الكرافت والكوشيه لأكياس التغليف: الطباعة، الأوزان، التشطيبات، الحمولة، والتكلفة — مع ما يفرضه مناخ جدة على قرارك.",
        category: "مقارنات",
        intent: "commercial",
        publishAt: "2026-10-06T19:58:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم الهدايا الدعائية والتغليف",
        image: "/images/custom-paper-bags-shopping-packaging.webp",
        imageAlt: "أكياس ورقية مخصصة للتغليف بخامتي الكرافت والكوشيه مطبوعة بشعارات تجارية في جدة",
        readTime: "11 دقيقة",
        primaryKeyword: "ورق كرافت أم كوشيه للتغليف",
    },
    {
        slug: "rent-vs-buy-booth",
        title: "تأجير أم شراء جناح المعرض؟ الحساب الاقتصادي",
        seoTitle: "تأجير أم شراء جناح المعرض؟ نقطة التعادل",
        excerpt: "الحساب الكامل لقرار تأجير جناح المعرض أو شرائه: التكلفة الأولى، التخزين، النقل، الصيانة، وتحديث الجرافيك — مع نقطة التعادل بالأرقام لجناح 18 و36 متراً مربعاً.",
        category: "مقارنات",
        intent: "commercial",
        publishAt: "2026-10-04T10:47:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المعارض والفعاليات",
        image: "/images/octanorm-system-booth-shell-scheme.webp",
        imageAlt: "جناح معرض نظامي مركّب داخل قاعة معارض في جدة يوضّح الفرق بين الجناح المستأجر والمملوك",
        readTime: "12 دقيقة",
        primaryKeyword: "تأجير أم شراء جناح المعرض",
    },
    {
        slug: "vinyl-brands-comparison",
        title: "فينيل 3M أم Avery أم Oracal؟ المقارنة التقنية الكاملة",
        seoTitle: "مقارنة أنواع الفينيل: 3M وAvery وOracal",
        excerpt: "مقارنة تقنية بين عائلات الفينيل الثلاث الأشهر — الكاست والكالندرد، تقنيات اللاصق، العمر الافتراضي في مناخ جدة، ونطاقات أسعار المتر المربع.",
        category: "مقارنات",
        intent: "commercial",
        publishAt: "2026-10-01T10:27:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم اللافتات والتغليف",
        image: "/images/commercial-vehicle-branding-car-wrapping-jeddah.webp",
        imageAlt: "سيارة تجارية مغلّفة بفينيل لاصق أثناء التركيب في ورشة بجدة",
        readTime: "12 دقيقة",
        primaryKeyword: "مقارنة أنواع الفينيل",
    },
    {
        slug: "signage-materials-comparison",
        title: "أكريليك أم ستانلس أم ألوكوبوند؟ مقارنة خامات اللافتات",
        seoTitle: "مقارنة خامات اللافتات: أكريليك أم ستانلس؟",
        excerpt: "مقارنة تقنية بين الأكريليك والستانلس ستيل والألوكوبوند في لافتات المحلات: العمر الافتراضي، سلوك كل خامة في حرارة جدة ورطوبتها المالحة، نطاقات التكلفة، ومتى يكون كل خيار هو الصحيح.",
        category: "مقارنات",
        intent: "commercial",
        publishAt: "2026-09-28T20:58:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم اللافتات والواجهات",
        image: "/images/3d-shop-signage-letters-acrylic-jeddah.webp",
        imageAlt: "حروف بارزة من الأكريليك مضاءة على واجهة محل في جدة",
        readTime: "12 دقيقة",
        primaryKeyword: "مقارنة خامات اللافتات",
    },
    {
        slug: "embroidery-vs-heat-transfer",
        title: "تطريز أم طباعة حرارية؟ دليل اختيار طريقة الطباعة على الملابس",
        seoTitle: "تطريز أم طباعة حرارية على الملابس؟",
        excerpt: "مقارنة عملية بين التطريز والفينيل الحراري وDTF والتسامي وسلك السكرين: أيها يناسب قماشك وكميتك وميزانيتك، ومتى يصمد الشعار على اليونيفورم اليومي في جدة.",
        category: "مقارنات",
        intent: "commercial",
        publishAt: "2026-09-25T09:58:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم الهدايا الترويجية والملابس",
        image: "/images/logo-printed-tshirts-embroidery-polo.webp",
        imageAlt: "قمصان بولو وتيشيرتات بشعارات شركات منفّذة بالتطريز والطباعة الحرارية في مطبعة بجدة",
        readTime: "10 دقائق",
        primaryKeyword: "تطريز أم طباعة حرارية",
    },
    {
        slug: "popup-vs-mediawall",
        title: "بوب أب أم ميديا وول أم خلفية مسرح؟ دليل الاختيار",
        seoTitle: "بوب أب أم ميديا وول؟ دليل الاختيار",
        excerpt: "مقارنة تقنية بين البوب أب والميديا وول وخلفية المسرح: المقاسات، الخامات، زمن التركيب، سلوك السطح أمام الكاميرا، وتكلفة إعادة الاستخدام. مع جداول تحسم القرار قبل حجز الفعالية.",
        category: "مقارنات",
        intent: "commercial",
        publishAt: "2026-09-22T20:22:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المعارض والفعاليات",
        image: "/images/pop-up-display-media-wall-background.webp",
        imageAlt: "خلفية بوب أب وميديا وول مطبوعة داخل قاعة فعاليات في جدة",
        readTime: "12 دقيقة",
        primaryKeyword: "بوب أب أم ميديا وول",
    },
    {
        slug: "logo-design-price-saudi",
        title: "كم سعر تصميم شعار احترافي في السعودية؟",
        seoTitle: "سعر تصميم شعار احترافي في السعودية 2026",
        excerpt: "نطاقات أسعار تصميم الشعار في السوق السعودي حسب مستوى المنفّذ وما يشمله العرض، مع جدول الملفات التي يجب أن تستلمها وكيف تقرأ عرض السعر قبل الدفع.",
        category: "أسعار",
        intent: "transactional",
        publishAt: "2026-09-20T09:53:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم التصميم والهوية البصرية",
        image: "/images/client-meeting-office-al-rawaj-jeddah.webp",
        imageAlt: "اجتماع مناقشة مقترحات تصميم شعار مع عميل في مكتب بوابة الرواج بحي الروضة في جدة",
        readTime: "13 دقيقة",
        primaryKeyword: "سعر تصميم شعار في السعودية",
    },
    {
        slug: "outdoor-banners-price-jeddah",
        title: "أسعار البنرات الخارجية والفلكس في جدة",
        seoTitle: "أسعار البنرات والفلكس في جدة 2026",
        excerpt: "تفكيك سعر المتر المربع للبنرات الخارجية في جدة حسب الخامة والوزن ونوع الحبر والتشطيب، مع البنود المخفية وعمر البنر الحقيقي تحت شمس الساحل.",
        category: "أسعار",
        intent: "transactional",
        publishAt: "2026-09-17T19:31:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم الطباعة الكبيرة واللافتات الخارجية",
        image: "/images/outdoor-flex-banner-printing-large-format.webp",
        imageAlt: "طباعة بنر فلكس خارجي كبير المقاس على ماكينة سولفنت في جدة",
        readTime: "12 دقيقة",
        primaryKeyword: "أسعار البنرات الخارجية في جدة",
    },
    {
        slug: "product-labels-price-jeddah",
        title: "أسعار طباعة ملصقات المنتجات في جدة",
        seoTitle: "أسعار ملصقات المنتجات في جدة 2026",
        excerpt: "تفكيك كامل لسعر ملصق المنتج في جدة: الخامة، الكمية، قالب القص، التشطيب، ونوع اللاصق المناسب للرطوبة الساحلية — مع جداول نطاقات سعرية وبنود يغفلها أغلب العروض.",
        category: "أسعار",
        intent: "transactional",
        publishAt: "2026-09-14T19:31:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم الملصقات والتغليف",
        image: "/images/custom-product-labels-roll-stickers-jeddah.webp",
        imageAlt: "ملصقات منتجات مطبوعة على رول بمقاسات وخامات مختلفة في مطبعة بجدة",
        readTime: "12 دقيقة",
        primaryKeyword: "أسعار ملصقات المنتجات في جدة",
    },
    {
        slug: "uniform-embroidery-price-jeddah",
        title: "أسعار الملابس الدعائية والتطريز في جدة",
        seoTitle: "أسعار الملابس الدعائية والتطريز بجدة 2026",
        excerpt: "كيف يُحتسب سعر التيشيرت والبولو واليونيفورم المطرّز في جدة: نطاقات الأسعار حسب الصنف والكمية، حساب التطريز بعدد الغرز، ومقارنة تقنيات الطباعة على القماش.",
        category: "أسعار",
        intent: "transactional",
        publishAt: "2026-09-12T15:31:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم الهدايا الدعائية والملابس",
        image: "/images/logo-printed-tshirts-embroidery-polo.webp",
        imageAlt: "تيشيرتات وبولو مطبوعة ومطرّزة بشعار شركة جاهزة للتسليم في جدة",
        readTime: "11 دقيقة",
        primaryKeyword: "أسعار الملابس الدعائية في جدة",
    },
    {
        slug: "ncr-books-price-jeddah",
        title: "أسعار طباعة دفاتر NCR والفواتير في جدة",
        seoTitle: "أسعار طباعة دفاتر NCR والفواتير بجدة 2026",
        excerpt: "نطاقات أسعار دفاتر NCR الكربونية في جدة حسب المقاس وعدد النسخ والكمية، مع شرح بنود العرض التي تصنع الفارق، ومتطلبات الفاتورة في السعودية.",
        category: "أسعار",
        intent: "transactional",
        publishAt: "2026-09-10T19:31:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المطبوعات التجارية والإدارية",
        image: "/images/ncr-invoice-books-receipts-printing.webp",
        imageAlt: "دفاتر NCR كربونية للفواتير والإيصالات بنسخ ملوّنة وترقيم تسلسلي مطبوعة في جدة",
        readTime: "13 دقيقة",
        primaryKeyword: "أسعار دفاتر NCR في جدة",
    },
    {
        slug: "flyers-brochures-price-jeddah",
        title: "أسعار طباعة الفلايرات والبروشورات في جدة",
        seoTitle: "أسعار طباعة الفلايرات والبروشورات بجدة",
        excerpt: "نطاقات أسعار واقعية لطباعة الفلايرات والمطويات في جدة حسب المقاس والكمية والورق والطي، مع جداول مقارنة ونقطة التعادل بين الأوفست والرقمي. تعرف قبل أن تدفع إن كان العرض الذي بين يديك منطقياً أم لا.",
        category: "أسعار",
        intent: "transactional",
        publishAt: "2026-09-08T18:53:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المطبوعات التجارية",
        image: "/images/advertising-flyers-brochures-tri-fold.webp",
        imageAlt: "فلايرات ومطويات ثلاثية الطي مطبوعة بألوان كاملة داخل مطبعة في جدة",
        readTime: "13 دقيقة",
        primaryKeyword: "أسعار طباعة الفلايرات في جدة",
    },
    {
        slug: "restaurant-menu-guide",
        title: "دليل تصميم وطباعة منيو المطعم: من المحتوى حتى الخامة",
        seoTitle: "دليل تصميم وطباعة منيو المطعم",
        excerpt: "كيف تصمّم منيو يزيد متوسط الفاتورة: ترتيب الأصناف، عرض الأسعار، اختيار الخامة المقاومة، والأخطاء التي تكلّف المطاعم يومياً.",
        category: "مطبوعات",
        intent: "commercial",
        publishAt: "2026-09-05T16:12:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المطبوعات التجارية",
        image: "/images/restaurant-menu-design-leather-cover.webp",
        imageAlt: "منيو مطعم بغلاف جلدي فاخر في جدة",
        readTime: "10 دقائق",
        primaryKeyword: "تصميم وطباعة منيو المطعم",
    },
    {
        slug: "brand-identity-guide",
        title: "الهوية البصرية للشركات: ما هي ولماذا الشعار وحده لا يكفي",
        seoTitle: "دليل الهوية البصرية للشركات",
        excerpt: "الفرق بين الشعار والهوية البصرية، مكوّنات الهوية المتكاملة، مراحل التنفيذ، والملفات التي يجب أن تستلمها.",
        category: "تصميم",
        intent: "informational",
        publishAt: "2026-09-02T11:41:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم التصميم",
        image: "/images/client-meeting-office-al-rawaj-jeddah.webp",
        imageAlt: "جلسة تصميم هوية بصرية في مكتب بجدة",
        readTime: "11 دقيقة",
        primaryKeyword: "الهوية البصرية للشركات",
    },
    {
        slug: "promotional-gifts-guide",
        title: "دليل اختيار الهدايا الدعائية للشركات: ما ينجح وما يُرمى",
        seoTitle: "دليل الهدايا الدعائية للشركات",
        excerpt: "كيف تختار هدية دعائية تبقى مستخدمة بدل أن تُرمى: معايير الاختيار، الميزانيات، المناسبات، وأخطاء تهدر ميزانيتك.",
        category: "هدايا",
        intent: "commercial",
        publishAt: "2026-08-30T18:23:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم الهدايا الدعائية",
        image: "/images/corporate-promotional-gifts-jeddah-items.webp",
        imageAlt: "مجموعة هدايا دعائية للشركات في جدة",
        readTime: "10 دقائق",
        primaryKeyword: "اختيار الهدايا الدعائية للشركات",
    },
    {
        slug: "saudi-exhibitions-calendar",
        title: "دليل المعارض التجارية في السعودية: كيف تخطّط لمشاركتك",
        seoTitle: "دليل المعارض التجارية في السعودية",
        excerpt: "خريطة قاعات المعارض في السعودية، الجدول الزمني الواقعي للتحضير، حساب الميزانية الكاملة، وقياس العائد من المشاركة.",
        category: "معارض",
        intent: "reference",
        publishAt: "2026-08-27T09:07:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المعارض والفعاليات",
        image: "/images/exhibition-booth-fabrication-design-jeddah.webp",
        imageAlt: "جناح معرض تجاري في السعودية",
        readTime: "12 دقيقة",
        primaryKeyword: "المعارض التجارية في السعودية",
    },
    {
        slug: "choose-printing-company-jeddah",
        title: "كيف تختار مطبعة موثوقة في جدة؟ 12 معياراً عملياً",
        seoTitle: "كيف تختار مطبعة موثوقة في جدة؟",
        excerpt: "معايير اختيار المطبعة المناسبة في جدة: الأسئلة التي تكشف الجودة، العلامات التحذيرية، وكيف تقارن العروض بذكاء بدل السعر وحده.",
        category: "أدلة إرشادية",
        intent: "commercial",
        publishAt: "2026-08-24T12:18:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم خدمة العملاء",
        image: "/images/rawaj-gate-printing-workshop-team-at-work.webp",
        imageAlt: "ورشة طباعة في جدة أثناء العمل",
        readTime: "11 دقيقة",
        primaryKeyword: "كيف تختار مطبعة في جدة",
    },
    {
        slug: "octanorm-vs-custom-booth",
        title: "جناح أوكتانورم أم مخصص؟ دليل الاختيار بالأرقام",
        seoTitle: "أوكتانورم أم جناح مخصص؟ المقارنة",
        excerpt: "مقارنة عملية بين الأجنحة النظامية والمخصصة: التكلفة، مدة التنفيذ، الأثر البصري، وإعادة الاستخدام — مع نقطة التعادل التي تحدد الأوفر.",
        category: "مقارنات",
        intent: "commercial",
        publishAt: "2026-08-21T17:34:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المعارض والفعاليات",
        image: "/images/octanorm-system-booth-shell-scheme.webp",
        imageAlt: "جناح أوكتانورم نظامي في معرض بجدة",
        readTime: "10 دقائق",
        primaryKeyword: "أوكتانورم أم جناح مخصص",
    },
    {
        slug: "shop-signage-price-jeddah",
        title: "كم سعر لافتة محل في جدة؟ دليل التكلفة حسب الخامة والمقاس",
        seoTitle: "سعر لافتة محل في جدة 2026",
        excerpt: "أسعار لافتات المحلات في جدة حسب الخامة (أكريليك، ستانلس، نيون) والمقاس ونوع الإضاءة، مع البنود المخفية وتكلفة التشغيل السنوية.",
        category: "أسعار",
        intent: "transactional",
        publishAt: "2026-08-19T10:52:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم اللافتات والتركيب",
        image: "/images/3d-shop-signage-letters-acrylic-jeddah.webp",
        imageAlt: "لافتة محل بحروف أكريليك مضيئة في جدة",
        readTime: "10 دقائق",
        primaryKeyword: "سعر لافتة محل في جدة",
    },
    {
        slug: "paper-weight-size-guide",
        title: "دليل أوزان ومقاسات الورق الشامل: من A0 إلى بطاقة العمل",
        seoTitle: "دليل أوزان ومقاسات الورق الشامل",
        excerpt: "مرجع كامل لمقاسات الورق القياسية (A، B، DL) وأوزان الجرامات واستخداماتها، مع جداول تحويل عملية لكل نوع مطبوعة.",
        category: "مرجعي",
        intent: "reference",
        publishAt: "2026-08-16T15:27:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم ما قبل الطباعة",
        image: "/images/printing-machines-digital-offset-equipment.webp",
        imageAlt: "أنواع وأوزان الورق في مطبعة بجدة",
        readTime: "11 دقيقة",
        primaryKeyword: "مقاسات الورق وأوزانه",
    },
    {
        slug: "coated-vs-linen-paper",
        title: "ورق كوشيه أم كتان؟ دليل اختيار خامة بطاقة العمل",
        seoTitle: "ورق كوشيه أم كتان لبطاقات العمل؟",
        excerpt: "مقارنة تفصيلية بين أنواع ورق بطاقات العمل: الكوشيه، الكتان، القطني، والكرافت — الملمس والتكلفة والقطاع المناسب لكل نوع.",
        category: "مقارنات",
        intent: "commercial",
        publishAt: "2026-08-14T08:12:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المطبوعات التجارية",
        image: "/images/luxury-business-cards-printing-jeddah.webp",
        imageAlt: "أنواع مختلفة من ورق بطاقات العمل",
        readTime: "8 دقائق",
        primaryKeyword: "ورق كوشيه أم كتان لبطاقات العمل",
    },
    {
        slug: "prepare-print-file-guide",
        title: "كيف تجهّز ملفك للطباعة بشكل صحيح؟ دليل خطوة بخطوة",
        seoTitle: "دليل تجهيز ملفات الطباعة الصحيح",
        excerpt: "الدليل العملي لتجهيز ملف طباعة خالٍ من الأخطاء: الدقة، الألوان، البليد، الخطوط، وصيغة التصدير النهائية.",
        category: "أدلة إرشادية",
        intent: "informational",
        publishAt: "2026-08-11T13:46:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم ما قبل الطباعة",
        image: "/images/printing-machines-digital-offset-equipment.webp",
        imageAlt: "تجهيز ملفات الطباعة في قسم ما قبل الطباعة بجدة",
        readTime: "10 دقائق",
        primaryKeyword: "كيف أجهز ملف الطباعة",
    },
    {
        slug: "vehicle-wrapping-price-jeddah",
        title: "أسعار تغليف السيارات في جدة 2026: الفينيل والتكلفة والعمر الافتراضي",
        seoTitle: "أسعار تغليف السيارات في جدة 2026",
        excerpt: "تكلفة تغليف السيارات في جدة حسب نوع الفينيل ومساحة التغطية، وكيف يؤثر مناخ جدة على العمر الافتراضي للتغليف.",
        category: "أسعار",
        intent: "transactional",
        publishAt: "2026-08-09T19:03:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم اللافتات والتغليف",
        image: "/images/commercial-vehicle-branding-car-wrapping-jeddah.webp",
        imageAlt: "سيارة تجارية مغلّفة بالفينيل في جدة",
        readTime: "10 دقائق",
        primaryKeyword: "أسعار تغليف السيارات في جدة",
    },
    {
        slug: "exhibition-booth-cost-saudi",
        title: "كم تكلفة تجهيز جناح معرض في السعودية؟ حساب المتر المربع 2026",
        seoTitle: "تكلفة تجهيز جناح معرض في السعودية",
        excerpt: "دليل تكلفة أجنحة المعارض بالمتر المربع: الفرق بين الأوكتانورم والمخصص، ما يشمله السعر، والبنود المخفية التي تفاجئ الشركات.",
        category: "أسعار",
        intent: "transactional",
        publishAt: "2026-08-06T10:27:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المعارض والفعاليات",
        image: "/images/custom-wooden-stand-jeddah-super-dome.webp",
        imageAlt: "جناح معرض خشبي مخصص في جدة سوبر دوم",
        readTime: "12 دقيقة",
        primaryKeyword: "تكلفة تجهيز جناح معرض في السعودية",
    },
    {
        slug: "offset-vs-digital-printing",
        title: "طباعة أوفست أم رقمية؟ الفرق الحقيقي ومتى تختار كلاً منهما",
        seoTitle: "الفرق بين الطباعة الأوفست والرقمية",
        excerpt: "مقارنة عملية بين الطباعة الأوفست والرقمية من حيث التكلفة والجودة والكمية والسرعة، مع نقطة التعادل التي تحدد الخيار الأوفر.",
        category: "مقارنات",
        intent: "informational",
        publishAt: "2026-07-24T16:52:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم الإنتاج",
        image: "/images/printing-machines-digital-offset-equipment.webp",
        imageAlt: "ماكينات الطباعة الرقمية والأوفست في ورشة بجدة",
        readTime: "9 دقائق",
        primaryKeyword: "الفرق بين الطباعة الأوفست والرقمية",
    },
    {
        slug: "roll-up-stand-price-jeddah",
        title: "أسعار رول أب ستاند في جدة 2026: المقاسات والخامات والتكلفة",
        seoTitle: "أسعار رول أب ستاند في جدة 2026",
        excerpt: "دليل كامل لأسعار الرول أب في جدة حسب المقاس ونوع الهيكل وخامة البانر، مع شرح الفرق بين الفئات ومتى تستحق الترقية.",
        category: "أسعار",
        intent: "transactional",
        publishAt: "2026-07-21T11:18:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المعارض والفعاليات",
        image: "/images/roll-up-stand-banner-85x200.webp",
        imageAlt: "رول أب ستاند بمقاس 85×200 سم جاهز للمعرض",
        readTime: "8 دقائق",
        primaryKeyword: "أسعار رول أب ستاند في جدة",
    },
    {
        slug: "shop-signage-municipality-rules-jeddah",
        title: "اشتراطات لوحات المحلات في أمانة جدة: الدليل الكامل 2026",
        seoTitle: "اشتراطات لوحات المحلات في جدة 2026",
        excerpt: "كل ما تحتاج معرفته قبل تركيب لافتة محلك في جدة: الاشتراطات النظامية، نسبة اللغة العربية، المقاسات المسموحة، خطوات التصريح، والمخالفات الشائعة.",
        category: "مرجعي",
        intent: "reference",
        publishAt: "2026-07-17T14:41:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم اللافتات والتركيب",
        image: "/images/3d-shop-signage-letters-acrylic-jeddah.webp",
        imageAlt: "لافتة محل ثلاثية الأبعاد مركّبة على واجهة في جدة",
        readTime: "11 دقيقة",
        primaryKeyword: "اشتراطات لوحات المحلات في جدة",
    },
    {
        slug: "business-cards-price-jeddah",
        title: "كم سعر طباعة كروت شخصية في جدة؟ دليل الأسعار الكامل 2026",
        seoTitle: "سعر طباعة كروت شخصية في جدة 2026",
        excerpt: "الأسعار الفعلية لطباعة بطاقات العمل في جدة حسب الخامة والكمية والتشطيب، مع جدول مقارنة، وما الذي يجعل السعر يرتفع أو ينخفض.",
        category: "أسعار",
        intent: "transactional",
        publishAt: "2026-07-14T09:34:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المطبوعات التجارية",
        image: "/images/luxury-business-cards-printing-jeddah.webp",
        imageAlt: "بطاقات عمل مطبوعة بتشطيبات مختلفة في جدة",
        readTime: "9 دقائق",
        primaryKeyword: "سعر طباعة كروت شخصية في جدة",
    },
];
/* ⬆️ AUTO-GENERATED — end */

/* ══════════════════════════════════════════════════════════
   منطق النشر المجدول — يعمل على الـ metadata وحدها (خفيف)
   ══════════════════════════════════════════════════════════ */

export function isPublished(meta: ArticleMeta, now: Date = new Date()): boolean {
    return new Date(meta.publishAt).getTime() <= now.getTime();
}

/** المقالات المنشورة، الأحدث أولاً */
export function getPublishedMeta(now: Date = new Date()): ArticleMeta[] {
    return ARTICLE_META.filter((m) => isPublished(m, now)).sort(
        (a, b) => new Date(b.publishAt).getTime() - new Date(a.publishAt).getTime()
    );
}

export function getMeta(slug: string): ArticleMeta | undefined {
    return ARTICLE_META.find((m) => m.slug === slug);
}

/** كل الـ slugs — للتوليد الساكن */
export function getAllSlugs(): string[] {
    return ARTICLE_META.map((m) => m.slug);
}

/** مقالات ذات صلة — يعمل على metadata فقط، بلا تحميل أي محتوى */
export function getRelatedMeta(
    slug: string,
    limit = 3,
    now: Date = new Date()
): ArticleMeta[] {
    const current = getMeta(slug);
    if (!current) return [];

    const published = getPublishedMeta(now).filter((m) => m.slug !== slug);
    const sameCategory = published.filter((m) => m.category === current.category);
    const sameIntent = published.filter(
        (m) => m.category !== current.category && m.intent === current.intent
    );

    return [...sameCategory, ...sameIntent, ...published]
        .filter((m, i, arr) => arr.findIndex((x) => x.slug === m.slug) === i)
        .slice(0, limit);
}

/** التصنيفات النشطة مع العدد */
export function getActiveCategories(now: Date = new Date()) {
    const counts = new Map<string, number>();
    for (const m of getPublishedMeta(now)) {
        counts.set(m.category, (counts.get(m.category) ?? 0) + 1);
    }
    return [...counts.entries()].map(([category, count]) => ({ category, count }));
}

export function getBlogStats(now: Date = new Date()) {
    const published = getPublishedMeta(now);
    return {
        published: published.length,
        upcoming: ARTICLE_META.length - published.length,
        total: ARTICLE_META.length,
        categories: getActiveCategories(now).length,
    };
}
