/* ⚠️ ملف مولَّد — لا تُعدّله يدوياً.
   المصدر: src/lib/articles/posts/*.ts
   التوليد: node scripts/generate-article-registry.mjs
   يضمّ مقالات 2026-08 فقط — انظر meta.ts للسبب. */

import type { ArticleMeta } from "../meta";

export const META_2026_08: ArticleMeta[] = [
    {
        slug: "outdoor-banners-price-jeddah",
        title: "أسعار البنرات الخارجية والفلكس في جدة",
        seoTitle: "أسعار البنرات والفلكس في جدة 2026",
        excerpt: "تفكيك سعر المتر المربع للبنرات الخارجية في جدة حسب الخامة والوزن ونوع الحبر والتشطيب، مع البنود المخفية وعمر البنر الحقيقي تحت شمس الساحل.",
        category: "أسعار",
        intent: "transactional",
        publishAt: "2026-08-31T09:55:00+03:00",
        dateModified: "2026-08-31",
        author: "فريق بوابة الرواج",
        authorRole: "قسم الطباعة الكبيرة واللافتات الخارجية",
        image: "/images/outdoor-flex-banner-printing-large-format.webp",
        imageAlt: "طباعة بنر فلكس خارجي كبير المقاس على ماكينة سولفنت في جدة",
        readTime: "15 دقيقة",
        primaryKeyword: "أسعار البنرات الخارجية في جدة",
    },
    {
        slug: "product-labels-price-jeddah",
        title: "أسعار طباعة ملصقات المنتجات في جدة",
        seoTitle: "أسعار ملصقات المنتجات في جدة 2026",
        excerpt: "تفكيك كامل لسعر ملصق المنتج في جدة: الخامة، الكمية، قالب القص، التشطيب، ونوع اللاصق المناسب للرطوبة الساحلية — مع جداول نطاقات سعرية وبنود يغفلها أغلب العروض.",
        category: "أسعار",
        intent: "transactional",
        publishAt: "2026-08-28T15:17:00+03:00",
        dateModified: "2026-08-28",
        author: "فريق بوابة الرواج",
        authorRole: "قسم الملصقات والتغليف",
        image: "/images/custom-product-labels-roll-stickers-jeddah.webp",
        imageAlt: "ملصقات منتجات مطبوعة على رول بمقاسات وخامات مختلفة في مطبعة بجدة",
        readTime: "14 دقيقة",
        primaryKeyword: "أسعار ملصقات المنتجات في جدة",
    },
    {
        slug: "uniform-embroidery-price-jeddah",
        title: "أسعار الملابس الدعائية والتطريز في جدة",
        seoTitle: "أسعار الملابس الدعائية والتطريز بجدة 2026",
        excerpt: "كيف يُحتسب سعر التيشيرت والبولو واليونيفورم المطرّز في جدة: نطاقات الأسعار حسب الصنف والكمية، حساب التطريز بعدد الغرز، ومقارنة تقنيات الطباعة على القماش.",
        category: "أسعار",
        intent: "transactional",
        publishAt: "2026-08-26T13:38:00+03:00",
        dateModified: "2026-08-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم الهدايا الدعائية والملابس",
        image: "/images/logo-printed-tshirts-embroidery-polo.webp",
        imageAlt: "تيشيرتات وبولو مطبوعة ومطرّزة بشعار شركة جاهزة للتسليم في جدة",
        readTime: "15 دقيقة",
        primaryKeyword: "أسعار الملابس الدعائية في جدة",
    },
    {
        slug: "ncr-books-price-jeddah",
        title: "أسعار طباعة دفاتر NCR والفواتير في جدة",
        seoTitle: "أسعار طباعة دفاتر NCR والفواتير بجدة 2026",
        excerpt: "نطاقات أسعار دفاتر NCR الكربونية في جدة حسب المقاس وعدد النسخ والكمية، مع شرح بنود العرض التي تصنع الفارق، ومتطلبات الفاتورة في السعودية.",
        category: "أسعار",
        intent: "transactional",
        publishAt: "2026-08-24T13:48:00+03:00",
        dateModified: "2026-08-24",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المطبوعات التجارية والإدارية",
        image: "/images/ncr-invoice-books-receipts-printing.webp",
        imageAlt: "دفاتر NCR كربونية للفواتير والإيصالات بنسخ ملوّنة وترقيم تسلسلي مطبوعة في جدة",
        readTime: "14 دقيقة",
        primaryKeyword: "أسعار دفاتر NCR في جدة",
    },
    {
        slug: "flyers-brochures-price-jeddah",
        title: "أسعار طباعة الفلايرات والبروشورات في جدة",
        seoTitle: "أسعار طباعة الفلايرات والبروشورات بجدة",
        excerpt: "نطاقات أسعار واقعية لطباعة الفلايرات والمطويات في جدة حسب المقاس والكمية والورق والطي، مع جداول مقارنة ونقطة التعادل بين الأوفست والرقمي. تعرف قبل أن تدفع إن كان العرض الذي بين يديك منطقياً أم لا.",
        category: "أسعار",
        intent: "transactional",
        publishAt: "2026-08-22T20:46:00+03:00",
        dateModified: "2026-08-22",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المطبوعات التجارية",
        image: "/images/advertising-flyers-brochures-tri-fold.webp",
        imageAlt: "فلايرات ومطويات ثلاثية الطي مطبوعة بألوان كاملة داخل مطبعة في جدة",
        readTime: "15 دقيقة",
        primaryKeyword: "أسعار طباعة الفلايرات في جدة",
    },
    {
        slug: "restaurant-menu-guide",
        title: "دليل تصميم وطباعة منيو المطعم: من المحتوى حتى الخامة",
        seoTitle: "دليل تصميم وطباعة منيو المطعم",
        excerpt: "كيف تصمّم منيو يزيد متوسط الفاتورة: ترتيب الأصناف، عرض الأسعار، اختيار الخامة المقاومة، والأخطاء التي تكلّف المطاعم يومياً.",
        category: "مطبوعات",
        intent: "commercial",
        publishAt: "2026-08-20T09:01:00+03:00",
        dateModified: "2026-08-20",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المطبوعات التجارية",
        image: "/images/restaurant-menu-design-leather-cover.webp",
        imageAlt: "منيو مطعم بغلاف جلدي فاخر في جدة",
        readTime: "5 دقائق",
        primaryKeyword: "تصميم وطباعة منيو المطعم",
    },
    {
        slug: "brand-identity-guide",
        title: "الهوية البصرية للشركات: ما هي ولماذا الشعار وحده لا يكفي",
        seoTitle: "دليل الهوية البصرية للشركات",
        excerpt: "الفرق بين الشعار والهوية البصرية، مكوّنات الهوية المتكاملة، مراحل التنفيذ، والملفات التي يجب أن تستلمها.",
        category: "تصميم",
        intent: "informational",
        publishAt: "2026-08-17T11:07:00+03:00",
        dateModified: "2026-08-17",
        author: "فريق بوابة الرواج",
        authorRole: "قسم التصميم",
        image: "/images/complete-brand-identity-system-spread.webp",
        imageAlt: "نظام هوية بصرية متكامل: دليل الهوية مفتوحاً مع مطبوعات ومنتجات موحّدة اللون",
        readTime: "4 دقائق",
        primaryKeyword: "الهوية البصرية للشركات",
    },
    {
        slug: "promotional-gifts-guide",
        title: "دليل اختيار الهدايا الدعائية للشركات: ما ينجح وما يُرمى",
        seoTitle: "دليل الهدايا الدعائية للشركات",
        excerpt: "كيف تختار هدية دعائية تبقى مستخدمة بدل أن تُرمى: معايير الاختيار، الميزانيات، المناسبات، وأخطاء تهدر ميزانيتك.",
        category: "هدايا",
        intent: "commercial",
        publishAt: "2026-08-15T17:06:00+03:00",
        dateModified: "2026-08-15",
        author: "فريق بوابة الرواج",
        authorRole: "قسم الهدايا الدعائية",
        image: "/images/corporate-promotional-gifts-jeddah-items.webp",
        imageAlt: "مجموعة هدايا دعائية للشركات في جدة",
        readTime: "4 دقائق",
        primaryKeyword: "اختيار الهدايا الدعائية للشركات",
    },
    {
        slug: "saudi-exhibitions-calendar",
        title: "دليل المعارض التجارية في السعودية: كيف تخطّط لمشاركتك",
        seoTitle: "دليل المعارض التجارية في السعودية",
        excerpt: "خريطة قاعات المعارض في السعودية، الجدول الزمني الواقعي للتحضير، حساب الميزانية الكاملة، وقياس العائد من المشاركة.",
        category: "معارض",
        intent: "reference",
        publishAt: "2026-08-13T15:17:00+03:00",
        dateModified: "2026-08-13",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المعارض والفعاليات",
        image: "/images/exhibition-booth-fabrication-design-jeddah.webp",
        imageAlt: "جناح معرض تجاري في السعودية",
        readTime: "4 دقائق",
        primaryKeyword: "المعارض التجارية في السعودية",
    },
    {
        slug: "choose-printing-company-jeddah",
        title: "كيف تختار مطبعة موثوقة في جدة؟ 12 معياراً عملياً",
        seoTitle: "كيف تختار مطبعة موثوقة في جدة؟",
        excerpt: "معايير اختيار المطبعة المناسبة في جدة: الأسئلة التي تكشف الجودة، العلامات التحذيرية، وكيف تقارن العروض بذكاء بدل السعر وحده.",
        category: "أدلة إرشادية",
        intent: "commercial",
        publishAt: "2026-08-11T11:10:00+03:00",
        dateModified: "2026-08-11",
        author: "فريق بوابة الرواج",
        authorRole: "قسم خدمة العملاء",
        image: "/images/rawaj-gate-printing-workshop-team-at-work.webp",
        imageAlt: "ورشة طباعة في جدة أثناء العمل",
        readTime: "4 دقائق",
        primaryKeyword: "كيف تختار مطبعة في جدة",
    },
    {
        slug: "octanorm-vs-custom-booth",
        title: "جناح أوكتانورم أم مخصص؟ دليل الاختيار بالأرقام",
        seoTitle: "أوكتانورم أم جناح مخصص؟ المقارنة",
        excerpt: "مقارنة عملية بين الأجنحة النظامية والمخصصة: التكلفة، مدة التنفيذ، الأثر البصري، وإعادة الاستخدام — مع نقطة التعادل التي تحدد الأوفر.",
        category: "مقارنات",
        intent: "commercial",
        publishAt: "2026-08-09T13:05:00+03:00",
        dateModified: "2026-08-09",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المعارض والفعاليات",
        image: "/images/octanorm-system-booth-shell-scheme.webp",
        imageAlt: "جناح أوكتانورم نظامي في معرض بجدة",
        readTime: "4 دقائق",
        primaryKeyword: "أوكتانورم أم جناح مخصص",
    },
    {
        slug: "shop-signage-price-jeddah",
        title: "كم سعر لافتة محل في جدة؟ دليل التكلفة حسب الخامة والمقاس",
        seoTitle: "سعر لافتة محل في جدة 2026",
        excerpt: "أسعار لافتات المحلات في جدة حسب الخامة (أكريليك، ستانلس، نيون) والمقاس ونوع الإضاءة، مع البنود المخفية وتكلفة التشغيل السنوية.",
        category: "أسعار",
        intent: "transactional",
        publishAt: "2026-08-07T11:49:00+03:00",
        dateModified: "2026-08-07",
        author: "فريق بوابة الرواج",
        authorRole: "قسم اللافتات والتركيب",
        image: "/images/3d-shop-signage-letters-acrylic-jeddah.webp",
        imageAlt: "لافتة محل بحروف أكريليك مضيئة في جدة",
        readTime: "4 دقائق",
        primaryKeyword: "سعر لافتة محل في جدة",
    },
    {
        slug: "paper-weight-size-guide",
        title: "دليل أوزان ومقاسات الورق الشامل: من A0 إلى بطاقة العمل",
        seoTitle: "دليل أوزان ومقاسات الورق الشامل",
        excerpt: "مرجع كامل لمقاسات الورق القياسية (A، B، DL) وأوزان الجرامات واستخداماتها، مع جداول تحويل عملية لكل نوع مطبوعة.",
        category: "مرجعي",
        intent: "reference",
        publishAt: "2026-08-05T16:00:00+03:00",
        dateModified: "2026-08-05",
        author: "فريق بوابة الرواج",
        authorRole: "قسم ما قبل الطباعة",
        image: "/images/paper-stock-weights-sizes-samples.webp",
        imageAlt: "عيّنات ورق بأوزان وملامس مختلفة مع مقاسات متدرجة من البوستر إلى الكرت",
        readTime: "4 دقائق",
        primaryKeyword: "مقاسات الورق وأوزانه",
    },
    {
        slug: "coated-vs-linen-paper",
        title: "ورق كوشيه أم كتان؟ دليل اختيار خامة بطاقة العمل",
        seoTitle: "ورق كوشيه أم كتان لبطاقات العمل؟",
        excerpt: "مقارنة تفصيلية بين أنواع ورق بطاقات العمل: الكوشيه، الكتان، القطني، والكرافت — الملمس والتكلفة والقطاع المناسب لكل نوع.",
        category: "مقارنات",
        intent: "commercial",
        publishAt: "2026-08-03T16:04:00+03:00",
        dateModified: "2026-08-03",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المطبوعات التجارية",
        image: "/images/coated-vs-linen-paper-texture-macro.webp",
        imageAlt: "مقارنة ماكرو بين ورق كوشيه ناعم وورق كتان بملمس منسوج تحت ضوء جانبي",
        readTime: "4 دقائق",
        primaryKeyword: "ورق كوشيه أم كتان لبطاقات العمل",
    },
];
