/* ⚠️ ملف مولَّد — لا تُعدّله يدوياً.
   المصدر: src/lib/articles/posts/*.ts
   التوليد: node scripts/generate-article-registry.mjs
   يضمّ مقالات 2026-11 فقط — انظر meta.ts للسبب. */

import type { ArticleMeta } from "../meta";

export const META_2026_11: ArticleMeta[] = [
    {
        slug: "product-label-compliance",
        title: "كيف تجهّز ملصق منتج مطابقاً للاشتراطات؟",
        seoTitle: "اشتراطات ملصقات المنتجات: دليل التجهيز",
        excerpt: "خريطة عملية لتجهيز بطاقة منتج مطابقة: من تحديد الجهة الرقابية المختصة بفئتك، إلى البيانات الإلزامية والباركود ومنطقة التواريخ، وصولاً إلى ملف طباعة لا يُرفض.",
        category: "أدلة إرشادية",
        intent: "informational",
        publishAt: "2026-11-29T16:56:00+03:00",
        dateModified: "2026-11-29",
        author: "فريق بوابة الرواج",
        authorRole: "قسم الملصقات والتغليف",
        image: "/images/product-label-compliance-inspection.webp",
        imageAlt: "فحص مطابقة ملصق منتج بعدسة مكبرة على برطمان مع باركود وجدول بيانات",
        readTime: "13 دقيقة",
        primaryKeyword: "اشتراطات ملصقات المنتجات",
    },
    {
        slug: "brochure-design-guide",
        title: "كيف تصمّم بروشوراً يُقرأ ولا يُرمى؟",
        seoTitle: "كيف تصمم بروشور احترافي: دليل عملي",
        excerpt: "من نوع الطي وخريطة اللوحات حتى كثافة النص والورق والتشطيب، دليل عملي لتصميم بروشور يفتحه المستلم ويُكمله.\nيشمل المقاسات القياسية، قاعدة تقصير اللوحة المطوية، قائمة تحقق قبل الإرسال للمطبعة، ونطاقات أسعار استرشادية في جدة.",
        category: "أدلة إرشادية",
        intent: "informational",
        publishAt: "2026-11-26T19:48:00+03:00",
        dateModified: "2026-11-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم التصميم والمطبوعات التجارية",
        image: "/images/brochure-layout-design-trifold-grid.webp",
        imageAlt: "تصميم بروشور ثلاثي الطي بشبكة تحريرية منظمة مع مسطرة وتابلت يعرض أعمدة التصميم",
        readTime: "13 دقيقة",
        primaryKeyword: "كيف تصمم بروشور احترافي",
    },
    {
        slug: "choose-booth-location",
        title: "كيف تختار موقع جناحك داخل المعرض؟",
        seoTitle: "اختيار موقع الجناح داخل المعرض: دليل عملي",
        excerpt: "دليل عملي لقراءة مخطط صالة المعرض قبل التوقيع: الفرق بين الموقع الخطي والزاوية والجزيرة، ومسار حركة الزوار، وعلامات الخطر التي تجعل الموقع الرخيص أغلى مما يبدو.",
        category: "أدلة إرشادية",
        intent: "informational",
        publishAt: "2026-11-24T15:55:00+03:00",
        dateModified: "2026-11-24",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المعارض والفعاليات",
        image: "/images/exhibition-floor-plan-booth-selection.webp",
        imageAlt: "اختيار موقع الجناح على مخطط أرضية معرض تجاري بوضع علامة على جناح ركني",
        readTime: "12 دقيقة",
        primaryKeyword: "اختيار موقع جناح المعرض",
    },
    {
        slug: "inhouse-vs-outsource-design",
        title: "فريق تصميم داخلي أم وكالة خارجية؟",
        seoTitle: "فريق تصميم داخلي أم وكالة خارجية؟",
        excerpt: "حساب صريح لتكلفة المصمم الداخلي مقابل الإسناد الخارجي في السوق السعودي، مع نقطة التعادل حسب حجم عملك الشهري ومصفوفة قرار جاهزة.",
        category: "مقارنات",
        intent: "commercial",
        publishAt: "2026-11-22T14:07:00+03:00",
        dateModified: "2026-11-22",
        author: "فريق بوابة الرواج",
        authorRole: "قسم التصميم والهوية البصرية",
        image: "/images/creative-agency-team-design-review.webp",
        imageAlt: "فريق وكالة إبداعية يراجع تصاميم مطبوعة وشرائح ألوان حول طاولة عمل",
        readTime: "12 دقيقة",
        primaryKeyword: "فريق تصميم داخلي أم وكالة",
    },
    {
        slug: "roll-vs-sheet-labels",
        title: "ملصقات رول أم شيت؟ دليل اختيار شكل الملصق",
        seoTitle: "ملصقات رول أم شيت؟ دليل اختيار الشكل",
        excerpt: "متى تطلب ملصقاتك على رول ومتى على أفرخ: المواصفات التي تُحسم قبل الطباعة، أثر الشكل على تكلفة اللصق، وما يفرضه مناخ جدة على التخزين.",
        category: "مقارنات",
        intent: "commercial",
        publishAt: "2026-11-20T20:31:00+03:00",
        dateModified: "2026-11-20",
        author: "فريق بوابة الرواج",
        authorRole: "قسم الملصقات والستيكرات",
        image: "/images/custom-product-labels-roll-stickers.webp",
        imageAlt: "ملصقات منتجات مخصصة على رول وأفرخ مطبوعة بشعارات وباركود في مطبعة بجدة",
        readTime: "12 دقيقة",
        primaryKeyword: "ملصقات رول أم شيت",
    },
    {
        slug: "full-vs-partial-wrap",
        title: "تغليف كامل أم جزئي للسيارة؟ الحساب والاختيار",
        seoTitle: "تغليف كامل أم جزئي: الفرق والتكلفة",
        excerpt: "مقارنة عملية بين التغليف الكامل والجزئي للمركبات: نسبة التغطية، التكلفة السنوية، أثر لون السيارة ومناخ جدة، ومصفوفة قرار جاهزة.",
        category: "مقارنات",
        intent: "commercial",
        publishAt: "2026-11-18T20:28:00+03:00",
        dateModified: "2026-11-18",
        author: "فريق بوابة الرواج",
        authorRole: "قسم اللافتات وبراندينج المركبات",
        image: "/images/vehicle-wrap-vinyl-installation-squeegee.webp",
        imageAlt: "تركيب فينيل تغليف السيارة بالسكويجي مع ظهور خط الفصل بين الجزء المغلّف والأصلي",
        readTime: "10 دقائق",
        primaryKeyword: "تغليف كامل أم جزئي",
    },
    {
        slug: "led-vs-neon-signage",
        title: "إضاءة LED أم نيون فلكس للافتات؟ المقارنة الكاملة",
        seoTitle: "LED أم نيون فلكس للافتات؟ مقارنة كاملة",
        excerpt: "مقارنة تقنية بين وحدات LED والنيون فلكس في إنارة اللافتات: كيف تعمل كل تقنية، الاستهلاك الكهربائي، السطوع، سلوكهما في حرارة جدة ورطوبتها المالحة، نطاقات التكلفة، ومتى يكون كل خيار هو الصحيح.",
        category: "مقارنات",
        intent: "commercial",
        publishAt: "2026-11-16T09:14:00+03:00",
        dateModified: "2026-11-16",
        author: "فريق بوابة الرواج",
        authorRole: "قسم اللافتات والواجهات",
        image: "/images/led-backlit-vs-neon-flex-signage-dusk.webp",
        imageAlt: "مقارنة إضاءة LED الخلفية الهالة وأنبوب النيون فلكس على واجهة محل وقت الغروب",
        readTime: "13 دقيقة",
        primaryKeyword: "LED أم نيون فلكس",
    },
    {
        slug: "glossy-vs-matte-lamination",
        title: "سلوفان لامع أم مطفي؟ دليل اختيار التشطيب",
        seoTitle: "سلوفان لامع أم مطفي؟ أيهما تختار",
        excerpt: "مقارنة عملية بين السلوفان اللامع والمطفي: أثر كل منهما على الألوان، البصمات، الخدوش، الكتابة، والسماكة المناسبة — مع دليل اختيار حسب نوع المطبوعة ومناخ جدة.",
        category: "مقارنات",
        intent: "commercial",
        publishAt: "2026-11-14T17:11:00+03:00",
        dateModified: "2026-11-14",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المطبوعات التجارية",
        image: "/images/glossy-vs-matte-lamination-comparison.webp",
        imageAlt: "مقارنة السلوفان اللامع والمطفي على بطاقتين متطابقتين تحت إضاءة جانبية",
        readTime: "13 دقيقة",
        primaryKeyword: "سلوفان لامع أم مطفي",
    },
    {
        slug: "laser-vs-print-gifts",
        title: "حفر ليزر أم طباعة على الهدايا الدعائية؟",
        seoTitle: "حفر ليزر أم طباعة على الهدايا الدعائية؟",
        excerpt: "مقارنة تقنية بين حفر الليزر وطباعة الباد والسكرين والرقمية UV على الأقلام والترامس والميداليات: أي خامة تقبل أي أسلوب، ولماذا لا يوجد حفر بلون شعارك، وما الذي يرفع الفاتورة فعلاً.",
        category: "مقارنات",
        intent: "commercial",
        publishAt: "2026-11-12T20:26:00+03:00",
        dateModified: "2026-11-12",
        author: "فريق بوابة الرواج",
        authorRole: "قسم الهدايا الترويجية والتخصيص",
        image: "/images/custom-printed-metal-plastic-pens.webp",
        imageAlt: "أقلام معدنية وبلاستيكية مخصصة بشعارات شركات بالحفر بالليزر والطباعة في مطبعة بجدة",
        readTime: "12 دقيقة",
        primaryKeyword: "حفر ليزر أم طباعة",
    },
    {
        slug: "rollup-vs-xbanner",
        title: "رول أب أم إكس بانر؟ مقارنة ستاندات المعارض المحمولة",
        seoTitle: "رول أب أم إكس بانر؟ مقارنة الستاندات",
        excerpt: "مقارنة تقنية بين الرول أب والإكس بانر: الهيكل من الداخل، المقاسات، الخامات، الثبات أمام الهواء، سلوكهما في مناخ جدة، والأسعار الاسترشادية. مع جدول تكلفة المرة الواحدة الذي يحسم القرار.",
        category: "مقارنات",
        intent: "commercial",
        publishAt: "2026-11-10T15:14:00+03:00",
        dateModified: "2026-11-10",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المعارض والفعاليات",
        image: "/images/rollup-vs-xbanner-stand-comparison.webp",
        imageAlt: "مقارنة رول أب ستاند بقاعدة ألومنيوم مع إكس بانر بقوائم متقاطعة",
        readTime: "12 دقيقة",
        primaryKeyword: "رول أب أم إكس بانر",
    },
    {
        slug: "wall-decals-price-jeddah",
        title: "أسعار الملصقات الجدارية وستيكرات الزجاج في جدة",
        seoTitle: "أسعار الملصقات الجدارية وستيكر الزجاج بجدة",
        excerpt: "تفكيك سعر المتر المربع للملصق الجداري وستيكر الزجاج في جدة: الفينيل المقصوص، المطبوع، الساتيه (الفروست)، أجرة التركيب، والحد الأدنى للطلب — مع جداول نطاقات وأمثلة حسابية كاملة.",
        category: "أسعار",
        intent: "transactional",
        publishAt: "2026-11-08T12:51:00+03:00",
        dateModified: "2026-11-08",
        author: "فريق بوابة الرواج",
        authorRole: "قسم اللافتات والملصقات",
        image: "/images/glass-window-frosted-sticker-branding.webp",
        imageAlt: "ستيكر زجاج ساتيه (فروست) مع شعار مقصوص على واجهة مكتب زجاجية في جدة",
        readTime: "12 دقيقة",
        primaryKeyword: "أسعار الملصقات الجدارية في جدة",
    },
    {
        slug: "paper-bags-price-jeddah",
        title: "أسعار الأكياس الورقية والتغليف الدعائي في جدة",
        seoTitle: "أسعار الأكياس الورقية والتغليف في جدة 2026",
        excerpt: "نطاقات أسعار الأكياس الورقية المطبوعة في جدة حسب المقاس والخامة والوزن والكمية، مع تفكيك بنود المقابض والتشطيبات وقالب التقطيع.",
        category: "أسعار",
        intent: "transactional",
        publishAt: "2026-11-06T19:38:00+03:00",
        dateModified: "2026-11-06",
        author: "فريق بوابة الرواج",
        authorRole: "قسم الهدايا الدعائية والتغليف",
        image: "/images/custom-paper-bags-shopping-packaging.webp",
        imageAlt: "أكياس ورقية مطبوعة بشعارات تجارية بمقاسات وخامات مختلفة للتغليف الدعائي في جدة",
        readTime: "14 دقيقة",
        primaryKeyword: "أسعار الأكياس الورقية في جدة",
    },
    {
        slug: "menu-price-jeddah",
        title: "كم سعر طباعة منيو مطعم في جدة؟",
        seoTitle: "كم سعر طباعة منيو مطعم في جدة؟ دليل 2026",
        excerpt: "نطاقات أسعار طباعة المنيو في جدة حسب النوع والخامة والكمية، مع تفكيك بنود التجليد والتشطيب التي تصنع فارق الضِعفين بين عرضين لنفس المواصفة.",
        category: "أسعار",
        intent: "transactional",
        publishAt: "2026-11-03T19:36:00+03:00",
        dateModified: "2026-11-03",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المطبوعات التجارية وخدمة المطاعم",
        image: "/images/restaurant-menu-formats-comparison.webp",
        imageAlt: "مقارنة صيغ المنيو: غلاف جلدي، كرت مغلّف، ثلاثي الطي، كليب بورد وتنت كارد",
        readTime: "12 دقيقة",
        primaryKeyword: "سعر طباعة منيو مطعم في جدة",
    },
];
