/* ⚠️ ملف مولَّد — لا تُعدّله يدوياً.
   المصدر: src/lib/articles/posts/*.ts
   التوليد: node scripts/generate-article-registry.mjs
   يضمّ مقالات 2026-09 فقط — انظر meta.ts للسبب. */

import type { ArticleMeta } from "../meta";

export const META_2026_09: ArticleMeta[] = [
    {
        slug: "print-campaign-planning",
        title: "كيف تخطّط لحملة مطبوعات متكاملة؟",
        seoTitle: "دليل تخطيط حملة مطبوعات متكاملة",
        excerpt: "منهجية عملية بست خطوات لبناء حملة مطبوعات مترابطة: تحديد الهدف، خريطة نقاط الاتصال، حساب الكميات، توزيع الميزانية، الجدول الزمني العكسي، وقياس النتيجة.",
        category: "أدلة إرشادية",
        intent: "informational",
        publishAt: "2026-09-29T10:44:00+03:00",
        dateModified: "2026-09-29",
        author: "فريق بوابة الرواج",
        authorRole: "قسم إدارة المشاريع",
        image: "/images/print-shop-exhibition-services-saudi-arabia.webp",
        imageAlt: "مطبوعات دعائية متكاملة لحملة تسويقية واحدة معروضة داخل مطبعة في جدة",
        readTime: "13 دقيقة",
        primaryKeyword: "تخطيط حملة مطبوعات",
    },
    {
        slug: "signage-maintenance-guide",
        title: "كيف تحافظ على لافتة محلك في مناخ جدة؟",
        seoTitle: "صيانة لافتات المحلات في مناخ جدة: دليل عملي",
        excerpt: "دليل عملي لصيانة لافتة محلك تحت شمس جدة ورطوبتها المالحة: جدول فحص وتنظيف بالدورية الصحيحة، مواد التنظيف المسموحة والممنوعة لكل خامة، أعطال الإنارة الشائعة وأسبابها. مع نطاقات تكلفة استرشادية للصيانة، وعلامات تقول إن الاستبدال صار أوفر من الإصلاح.",
        category: "أدلة إرشادية",
        intent: "informational",
        publishAt: "2026-09-27T10:40:00+03:00",
        dateModified: "2026-09-27",
        author: "فريق بوابة الرواج",
        authorRole: "قسم اللافتات والواجهات",
        image: "/images/signage-maintenance-cleaning-led-service.webp",
        imageAlt: "صيانة لافتة محل: تنظيف اللوحة واستبدال وحدة LED من فتحة الصيانة",
        readTime: "13 دقيقة",
        primaryKeyword: "صيانة لافتات المحلات",
    },
    {
        slug: "write-design-brief",
        title: "كيف تكتب بريف تصميم يوفّر عليك الوقت والمال؟",
        seoTitle: "كيف تكتب بريف تصميم احترافي",
        excerpt: "الوثيقة التي تختصر جولات التعديل وتمنع الجدل مع المصمم: عناصرها العشرة، نموذج جاهز للنسخ، وقائمة تحقق قبل الإرسال.",
        category: "أدلة إرشادية",
        intent: "informational",
        publishAt: "2026-09-25T18:41:00+03:00",
        dateModified: "2026-09-25",
        author: "فريق بوابة الرواج",
        authorRole: "قسم التصميم والهوية البصرية",
        image: "/images/writing-design-brief-form-moodboard.webp",
        imageAlt: "تعبئة نموذج بريف تصميم بقلم حبر مع مود بورد قصاصات ألوان وبطاقات مرجعية",
        readTime: "12 دقيقة",
        primaryKeyword: "كيف تكتب بريف تصميم",
    },
    {
        slug: "vehicle-wrap-design-guide",
        title: "كيف تجهّز تصميم تغليف السيارة؟ دليل المصمم",
        seoTitle: "دليل تصميم تغليف السيارات للمصممين",
        excerpt: "من قالب المركبة إلى ملف الطباعة النهائي: المقاييس والدقة والألوان والمناطق الممنوعة وأحجام الخطوط في تصميم تغليف السيارات.",
        category: "أدلة إرشادية",
        intent: "informational",
        publishAt: "2026-09-23T10:33:00+03:00",
        dateModified: "2026-09-23",
        author: "فريق بوابة الرواج",
        authorRole: "قسم التصميم وبراندينج المركبات",
        image: "/images/vehicle-wrap-design-template-workstation.webp",
        imageAlt: "تصميم تغليف سيارة على قالب جانبي ثلاثي الأبعاد مع خطوط إرشاد للأبواب وأقواس العجلات",
        readTime: "12 دقيقة",
        primaryKeyword: "تصميم تغليف السيارات",
    },
    {
        slug: "gift-selection-by-occasion",
        title: "كيف تختار الهدية الدعائية المناسبة لكل مناسبة؟",
        seoTitle: "اختيار الهدية الدعائية حسب المناسبة",
        excerpt: "دليل عملي لاختيار الهدية الدعائية حسب المناسبة: رمضان، يوم التأسيس، اليوم الوطني، الافتتاحات، المعارض، نهاية السنة المالية، وتكريم الموظفين.\nمع جدول توقيت الطلب، نطاقات ميزانية استرشادية، وما يفسد الهدية في مناخ جدة.",
        category: "أدلة إرشادية",
        intent: "informational",
        publishAt: "2026-09-21T17:27:00+03:00",
        dateModified: "2026-09-21",
        author: "فريق بوابة الرواج",
        authorRole: "قسم الهدايا الدعائية والمناسبات",
        image: "/images/corporate-gift-selection-consultation.webp",
        imageAlt: "اختيار الهدية الدعائية من صينية عيّنات على طاولة اجتماعات مع عرض خيارات على تابلت",
        readTime: "11 دقيقة",
        primaryKeyword: "اختيار الهدية الدعائية للمناسبات",
    },
    {
        slug: "design-business-card-guide",
        title: "كيف تصمّم بطاقة عمل احترافية؟ دليل عملي",
        seoTitle: "كيف تصمم بطاقة عمل احترافية: دليل عملي",
        excerpt: "خطوات تصميم بطاقة العمل من المقاس وحد النزيف حتى الخطوط والألوان والورق والتشطيبات، مع قائمة تحقق قبل إرسال الملف للمطبعة.",
        category: "أدلة إرشادية",
        intent: "informational",
        publishAt: "2026-09-19T15:52:00+03:00",
        dateModified: "2026-09-19",
        author: "فريق بوابة الرواج",
        authorRole: "قسم التصميم والتجهيز الطباعي",
        image: "/images/business-card-design-sketches-process.webp",
        imageAlt: "عملية تصميم بطاقة عمل: اسكتشات على ورق شفاف، تابلت وموك أب مطبوع للمقارنة",
        readTime: "12 دقيقة",
        primaryKeyword: "كيف تصمم بطاقة عمل احترافية",
    },
    {
        slug: "kraft-vs-coated-packaging",
        title: "ورق كرافت أم كوشيه للتغليف؟ دليل اختيار خامة الأكياس",
        seoTitle: "ورق كرافت أم كوشيه للتغليف؟ دليل الاختيار",
        excerpt: "مقارنة عملية بين ورق الكرافت والكوشيه لأكياس التغليف: الطباعة، الأوزان، التشطيبات، الحمولة، والتكلفة — مع ما يفرضه مناخ جدة على قرارك.",
        category: "مقارنات",
        intent: "commercial",
        publishAt: "2026-09-16T21:17:00+03:00",
        dateModified: "2026-09-16",
        author: "فريق بوابة الرواج",
        authorRole: "قسم الهدايا الدعائية والتغليف",
        image: "/images/kraft-vs-coated-paper-bag-comparison.webp",
        imageAlt: "مقارنة كيس ورقي كرافت بني بمقبض مجدول وكيس كوشيه أبيض لامع بشريط ساتان",
        readTime: "11 دقيقة",
        primaryKeyword: "ورق كرافت أم كوشيه للتغليف",
    },
    {
        slug: "rent-vs-buy-booth",
        title: "تأجير أم شراء جناح المعرض؟ الحساب الاقتصادي",
        seoTitle: "تأجير أم شراء جناح المعرض؟ نقطة التعادل",
        excerpt: "الحساب الكامل لقرار تأجير جناح المعرض أو شرائه: التكلفة الأولى، التخزين، النقل، الصيانة، وتحديث الجرافيك — مع نقطة التعادل بالأرقام لجناح 18 و36 متراً مربعاً.",
        category: "مقارنات",
        intent: "commercial",
        publishAt: "2026-09-14T18:49:00+03:00",
        dateModified: "2026-09-14",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المعارض والفعاليات",
        image: "/images/exhibition-booth-storage-warehouse-modular.webp",
        imageAlt: "تخزين مكوّنات جناح معرض معياري في مستودع مقابل فريق يركّب الجناح",
        readTime: "12 دقيقة",
        primaryKeyword: "تأجير أم شراء جناح المعرض",
    },
    {
        slug: "vinyl-brands-comparison",
        title: "فينيل 3M أم Avery أم Oracal؟ المقارنة التقنية الكاملة",
        seoTitle: "مقارنة أنواع الفينيل: 3M وAvery وOracal",
        excerpt: "مقارنة تقنية بين عائلات الفينيل الثلاث الأشهر — الكاست والكالندرد، تقنيات اللاصق، العمر الافتراضي في مناخ جدة، ونطاقات أسعار المتر المربع.",
        category: "مقارنات",
        intent: "commercial",
        publishAt: "2026-09-12T20:41:00+03:00",
        dateModified: "2026-09-12",
        author: "فريق بوابة الرواج",
        authorRole: "قسم اللافتات والتغليف",
        image: "/images/cast-vinyl-film-rolls-swatches.webp",
        imageAlt: "بكرات فينيل مصبوب بألوان وتشطيبات مختلفة مع مروحة عيّنات لامع ومطفي وملمسي",
        readTime: "12 دقيقة",
        primaryKeyword: "مقارنة أنواع الفينيل",
    },
    {
        slug: "signage-materials-comparison",
        title: "أكريليك أم ستانلس أم ألوكوبوند؟ مقارنة خامات اللافتات",
        seoTitle: "مقارنة خامات اللافتات: أكريليك أم ستانلس؟",
        excerpt: "مقارنة تقنية بين الأكريليك والستانلس ستيل والألوكوبوند في لافتات المحلات: العمر الافتراضي، سلوك كل خامة في حرارة جدة ورطوبتها المالحة، نطاقات التكلفة، ومتى يكون كل خيار هو الصحيح.",
        category: "مقارنات",
        intent: "commercial",
        publishAt: "2026-09-10T09:56:00+03:00",
        dateModified: "2026-09-10",
        author: "فريق بوابة الرواج",
        authorRole: "قسم اللافتات والواجهات",
        image: "/images/acrylic-steel-aluminium-3d-letters-comparison.webp",
        imageAlt: "مقارنة حروف بارزة بثلاث خامات: أكريليك شفاف سميك، ستانلس مشكّل وألوكوبوند خفيف",
        readTime: "12 دقيقة",
        primaryKeyword: "مقارنة خامات اللافتات",
    },
    {
        slug: "embroidery-vs-heat-transfer",
        title: "تطريز أم طباعة حرارية؟ دليل اختيار طريقة الطباعة على الملابس",
        seoTitle: "تطريز أم طباعة حرارية على الملابس؟",
        excerpt: "مقارنة عملية بين التطريز والفينيل الحراري وDTF والتسامي وسلك السكرين: أيها يناسب قماشك وكميتك وميزانيتك، ومتى يصمد الشعار على اليونيفورم اليومي في جدة.",
        category: "مقارنات",
        intent: "commercial",
        publishAt: "2026-09-08T10:51:00+03:00",
        dateModified: "2026-09-08",
        author: "فريق بوابة الرواج",
        authorRole: "قسم الهدايا الترويجية والملابس",
        image: "/images/embroidery-vs-heat-transfer-machines.webp",
        imageAlt: "مقارنة التطريز الآلي والطباعة الحرارية على بولو وتيشرت داخل ورشة إنتاج",
        readTime: "10 دقائق",
        primaryKeyword: "تطريز أم طباعة حرارية",
    },
    {
        slug: "popup-vs-mediawall",
        title: "بوب أب أم ميديا وول أم خلفية مسرح؟ دليل الاختيار",
        seoTitle: "بوب أب أم ميديا وول؟ دليل الاختيار",
        excerpt: "مقارنة تقنية بين البوب أب والميديا وول وخلفية المسرح: المقاسات، الخامات، زمن التركيب، سلوك السطح أمام الكاميرا، وتكلفة إعادة الاستخدام. مع جداول تحسم القرار قبل حجز الفعالية.",
        category: "مقارنات",
        intent: "commercial",
        publishAt: "2026-09-06T09:10:00+03:00",
        dateModified: "2026-09-06",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المعارض والفعاليات",
        image: "/images/pop-up-display-media-wall-background.webp",
        imageAlt: "خلفية بوب أب وميديا وول مطبوعة داخل قاعة فعاليات في جدة",
        readTime: "12 دقيقة",
        primaryKeyword: "بوب أب أم ميديا وول",
    },
    {
        slug: "logo-design-price-saudi",
        title: "كم سعر تصميم شعار احترافي في السعودية؟",
        seoTitle: "سعر تصميم شعار احترافي في السعودية 2026",
        excerpt: "نطاقات أسعار تصميم الشعار في السوق السعودي حسب مستوى المنفّذ وما يشمله العرض، مع جدول الملفات التي يجب أن تستلمها وكيف تقرأ عرض السعر قبل الدفع.",
        category: "أسعار",
        intent: "transactional",
        publishAt: "2026-09-03T09:54:00+03:00",
        dateModified: "2026-09-03",
        author: "فريق بوابة الرواج",
        authorRole: "قسم التصميم والهوية البصرية",
        image: "/images/client-meeting-office-al-rawaj-jeddah.webp",
        imageAlt: "اجتماع مناقشة مقترحات تصميم شعار مع عميل في مكتب بوابة الرواج بحي الروضة في جدة",
        readTime: "13 دقيقة",
        primaryKeyword: "سعر تصميم شعار في السعودية",
    },
];
