/* ⚠️ ملف مولَّد — لا تُعدّله يدوياً.
   المصدر: src/lib/articles/posts/*.ts
   التوليد: node scripts/generate-article-registry.mjs
   يضمّ مقالات 2026-12 فقط — انظر meta.ts للسبب. */

import type { ArticleMeta } from "../meta";

export const META_2026_12: ArticleMeta[] = [
    {
        slug: "salon-spa-printing",
        title: "مطبوعات صالونات التجميل والسبا",
        seoTitle: "مطبوعات صالونات التجميل والسبا: دليل كامل",
        excerpt: "كل مطبوعة يحتاجها الصالون أو السبا: ملصقات المنتجات، قوائم الأسعار، كروت المواعيد والولاء، قسائم الهدايا، وستيكرات الخصوصية. مع الخامات التي تتحمّل الزيوت والبخار ورطوبة جدة، ونطاقات أسعار استرشادية.",
        category: "مطبوعات",
        intent: "commercial",
        publishAt: "2026-12-30T13:43:00+03:00",
        dateModified: "2026-12-30",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المطبوعات التجارية وملصقات المنتجات",
        image: "/images/salon-spa-reception-print-collateral.webp",
        imageAlt: "استقبال صالون وسبا: بطاقات مواعيد، كرت أسعار، مغلفات قسائم هدايا وملصقات منتجات",
        readTime: "13 دقيقة",
        primaryKeyword: "مطبوعات صالونات التجميل",
    },
    {
        slug: "gym-fitness-printing",
        title: "مطبوعات الصالات الرياضية والنوادي",
        seoTitle: "مطبوعات الصالات الرياضية: الخامات والأسعار",
        excerpt: "ما يحتاجه النادي الرياضي من لافتات وملصقات معدات وبطاقات عضوية وملابس فريق، بأي خامة تتحمّل العرق والمطهّرات ورطوبة جدة — مع نطاقات أسعار استرشادية.",
        category: "مطبوعات",
        intent: "commercial",
        publishAt: "2026-12-28T14:06:00+03:00",
        dateModified: "2026-12-28",
        author: "فريق بوابة الرواج",
        authorRole: "قسم اللافتات والمطبوعات التشغيلية",
        image: "/images/gym-fitness-branding-apparel-interior.webp",
        imageAlt: "صالة رياضية: تيشرتات تدريب مطوية، مناشف، زجاجة ماء ولوحة جدارية تحفيزية",
        readTime: "14 دقيقة",
        primaryKeyword: "مطبوعات الصالات الرياضية",
    },
    {
        slug: "business-card-styles",
        title: "أنماط بطاقات العمل حول العالم: دليل مرئي",
        seoTitle: "أنماط بطاقات العمل حول العالم ومقاساتها",
        excerpt: "خريطة مقاسات بطاقة العمل في السعودية وأوروبا وأمريكا واليابان والصين، ومنطق كل نمط تصميمي، والأشكال والخامات التي تُبنى عليها، وكيف تختار النمط المناسب لنشاطك.",
        category: "مرجعي",
        intent: "reference",
        publishAt: "2026-12-25T12:08:00+03:00",
        dateModified: "2026-12-25",
        author: "فريق بوابة الرواج",
        authorRole: "قسم التصميم والهوية البصرية",
        image: "/images/business-card-shapes-finishes-variety.webp",
        imageAlt: "بطاقات أعمال بأشكال وتشطيبات متنوعة: مربعة، عمودية، ثلاثية الطبقات بحافة ملوّنة وقص خاص",
        readTime: "13 دقيقة",
        primaryKeyword: "أنماط بطاقات العمل",
    },
    {
        slug: "banner-sizes-guide",
        title: "دليل مقاسات البنرات واللوحات الإعلانية",
        seoTitle: "مقاسات البنرات واللوحات الإعلانية",
        excerpt: "المقاسات القياسية للرول أب وبنرات الفليكس والخلفيات وبنرات الأعمدة، مع دقة الملف المطلوبة عند كل مسافة مشاهدة، والهوامش والعيون وطريقة التثبيت التي تصمد في مناخ جدة.",
        category: "مرجعي",
        intent: "reference",
        publishAt: "2026-12-23T20:54:00+03:00",
        dateModified: "2026-12-23",
        author: "فريق بوابة الرواج",
        authorRole: "قسم الطباعة كبيرة المقاس واللافتات",
        image: "/images/banner-size-measuring-wide-format-workshop.webp",
        imageAlt: "قياس بنر مطبوع بشريط قياس في ورشة طباعة عريضة مع عيّنات بمقاسات متدرجة",
        readTime: "14 دقيقة",
        primaryKeyword: "مقاسات البنرات",
    },
    {
        slug: "file-formats-guide",
        title: "دليل صيغ الملفات للطباعة والتصميم",
        seoTitle: "دليل صيغ ملفات الطباعة والتصميم",
        excerpt: "مرجع كامل لصيغ الملفات في الطباعة والدعاية: PDF وAI وTIFF وEPS وDXF وغيرها.\nمتى تستخدم كل صيغة، ومتى تكون خطأً مكلفاً، وما الذي تطلبه من مصممك بالضبط.",
        category: "مرجعي",
        intent: "reference",
        publishAt: "2026-12-21T08:13:00+03:00",
        dateModified: "2026-12-21",
        author: "فريق بوابة الرواج",
        authorRole: "قسم ما قبل الطباعة",
        image: "/images/vector-file-formats-print-workflow.webp",
        imageAlt: "ملف فيكتور على الشاشة بنقاط تحكم ومنحنيات بيزييه مع وسائط تخزين وبروفات مطبوعة",
        readTime: "13 دقيقة",
        primaryKeyword: "صيغ ملفات الطباعة",
    },
    {
        slug: "uniform-fabrics-guide",
        title: "دليل أقمشة الزي الموحد: الخصائص والاستخدامات",
        seoTitle: "أقمشة الزي الموحد: الخصائص والاستخدامات",
        excerpt: "مرجع عملي لأقمشة اليونيفورم: الألياف والمخاليط، الفرق بين المحبوك والمنسوج، أوزان GSM المناسبة لكل قطعة، وأي قماش يصمد في حرارة جدة ورطوبتها مع تنفيذ الشعار عليه.",
        category: "مرجعي",
        intent: "reference",
        publishAt: "2026-12-18T15:28:00+03:00",
        dateModified: "2026-12-18",
        author: "فريق بوابة الرواج",
        authorRole: "قسم الملابس الدعائية والزي الموحد",
        image: "/images/uniform-fabric-swatch-comparison.webp",
        imageAlt: "عيّنات أقمشة الزي الموحد: بيكيه، بوبلين، تويل، مِش بوليستر وفليس",
        readTime: "14 دقيقة",
        primaryKeyword: "أقمشة الزي الموحد",
    },
    {
        slug: "promotional-gifts-catalog",
        title: "كتالوج الهدايا الدعائية: 40 صنفاً بالتفصيل",
        seoTitle: "كتالوج الهدايا الدعائية: 40 صنفاً",
        excerpt: "مرجع مفصّل لأربعين صنفاً من الهدايا الدعائية المتداولة في السوق السعودي: الخامة، الحد الأدنى للطلب، طريقة التخصيص، ونطاق السعر الاسترشادي لكل صنف.",
        category: "مرجعي",
        intent: "reference",
        publishAt: "2026-12-16T12:55:00+03:00",
        dateModified: "2026-12-16",
        author: "فريق بوابة الرواج",
        authorRole: "قسم الهدايا الدعائية والمشتريات",
        image: "/images/promotional-gifts-catalog-overhead-range.webp",
        imageAlt: "كتالوج هدايا دعائية: أقلام، باور بانك، فلاشات، أكواب، حقائب، كابات وميداليات",
        readTime: "13 دقيقة",
        primaryKeyword: "أصناف الهدايا الدعائية",
    },
    {
        slug: "packaging-materials-guide",
        title: "دليل خامات التغليف: من الكرافت إلى البلاستيك",
        seoTitle: "خامات التغليف: دليل الورق والبلاستيك",
        excerpt: "مرجع عملي لخامات التغليف المتاحة في السوق السعودي: الورق والكرتون والأفلام البلاستيكية والأغشية المركّبة — أين تنجح كل خامة، وأين تفشل، وكم تكلف تقريباً.",
        category: "مرجعي",
        intent: "reference",
        publishAt: "2026-12-14T19:41:00+03:00",
        dateModified: "2026-12-14",
        author: "فريق بوابة الرواج",
        authorRole: "قسم التغليف والهدايا الدعائية",
        image: "/images/packaging-material-samples-comparison.webp",
        imageAlt: "عيّنات خامات التغليف: كرتون مضلّع، دوبلكس، كرافت، بلاستيك شفاف وكرتون مطلي",
        readTime: "13 دقيقة",
        primaryKeyword: "خامات التغليف",
    },
    {
        slug: "jeddah-districts-guide",
        title: "دليل أحياء جدة التجارية: أين تفتح محلك؟",
        seoTitle: "دليل أحياء جدة التجارية للمحال",
        excerpt: "خريطة عملية لأحياء جدة التجارية: طابع كل منطقة، الأنشطة التي تناسبها، وطريقة قياس ميدانية للموقع قبل توقيع العقد — مع أثر الحي على اللوحة والواجهة.",
        category: "مرجعي",
        intent: "reference",
        publishAt: "2026-12-12T12:10:00+03:00",
        dateModified: "2026-12-12",
        author: "فريق بوابة الرواج",
        authorRole: "قسم اللافتات وهوية المحال",
        image: "/images/jeddah-commercial-district-aerial-golden-hour.webp",
        imageAlt: "منظر جوي لحي تجاري في جدة وقت الغروب: شوارع نخيل ومبانٍ حديثة والبحر الأحمر",
        readTime: "12 دقيقة",
        primaryKeyword: "أحياء جدة التجارية",
    },
    {
        slug: "stage-backdrop-guide",
        title: "كيف تجهّز خلفية مسرح لفعاليتك؟",
        seoTitle: "كيف تجهّز خلفية مسرح لفعاليتك؟ دليل عملي",
        excerpt: "دليل تنفيذي لتجهيز خلفية مسرح: قياس القاعة، حساب المقاس، اختيار الهيكل والخامة، تجهيز ملف الطباعة، والتنسيق مع إدارة القاعة. مع جداول مقاسات وجدول زمني وأسعار استرشادية.",
        category: "أدلة إرشادية",
        intent: "informational",
        publishAt: "2026-12-10T21:20:00+03:00",
        dateModified: "2026-12-10",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المعارض والفعاليات",
        image: "/images/event-stage-backdrop-production-jeddah.webp",
        imageAlt: "تجهيز خلفية مسرح مطبوعة على هيكل تراس داخل قاعة فعاليات في جدة",
        readTime: "14 دقيقة",
        primaryKeyword: "تجهيز خلفية مسرح",
    },
    {
        slug: "print-budget-planning",
        title: "كيف تضع ميزانية مطبوعات سنوية لشركتك؟",
        seoTitle: "دليل ميزانية المطبوعات السنوية للشركات",
        excerpt: "منهجية عملية لبناء ميزانية مطبوعات سنوية قابلة للصرف: خط أساس من مصروف السنة الماضية، تصنيف البنود إلى أربع سلال، حساب معدل الاستهلاك ونقطة إعادة الطلب، وتوزيع الصرف على تقويم السنة بدل اثني عشر شهراً متساوية.",
        category: "أدلة إرشادية",
        intent: "informational",
        publishAt: "2026-12-08T15:07:00+03:00",
        dateModified: "2026-12-08",
        author: "فريق بوابة الرواج",
        authorRole: "قسم التخطيط وإدارة الحسابات",
        image: "/images/annual-print-budget-planning-desk.webp",
        imageAlt: "تخطيط ميزانية المطبوعات: جدول أرقام مطبوع، آلة حاسبة ورسم بياني وعيّنات مصنّفة",
        readTime: "13 دقيقة",
        primaryKeyword: "ميزانية المطبوعات السنوية",
    },
    {
        slug: "arabic-typography-guide",
        title: "الخط العربي في التصميم التجاري: دليل الاختيار",
        seoTitle: "دليل اختيار الخط العربي في التصميم التجاري",
        excerpt: "كيف تختار خطاً عربياً يصلح للافتة ولبطاقة العمل وللمنيو معاً، وما الفرق التقني بين العائلات، وأين تُفسد الأخطاء الشائعة شكل النص عند الطباعة والتنفيذ.",
        category: "أدلة إرشادية",
        intent: "informational",
        publishAt: "2026-12-06T20:16:00+03:00",
        dateModified: "2026-12-06",
        author: "فريق بوابة الرواج",
        authorRole: "قسم التصميم والهوية البصرية",
        image: "/images/arabic-calligraphy-typography-craft.webp",
        imageAlt: "الخط العربي: أقلام قصب، محبرة نحاسية وأوراق بضربات خطية زخرفية بجوار تابلت",
        readTime: "14 دقيقة",
        primaryKeyword: "الخط العربي في التصميم",
    },
    {
        slug: "color-psychology-branding",
        title: "سيكولوجيا الألوان في الهوية التجارية السعودية",
        seoTitle: "سيكولوجيا الألوان في الهوية التجارية",
        excerpt: "كيف تختار ألوان علامتك بقرار مبني على السياق السعودي والتمايز عن المنافسين وقابلية التنفيذ، لا على الذوق الشخصي — مع اختبارات عملية قبل اعتماد اللون.",
        category: "أدلة إرشادية",
        intent: "informational",
        publishAt: "2026-12-04T17:06:00+03:00",
        dateModified: "2026-12-04",
        author: "فريق بوابة الرواج",
        authorRole: "قسم الهوية البصرية والتصميم",
        image: "/images/color-psychology-branding-palette-cards.webp",
        imageAlt: "بطاقات ألوان كبيرة بقوس متدرّج مع مطبوعات هوية موضوعة على الألوان المطابقة",
        readTime: "14 دقيقة",
        primaryKeyword: "سيكولوجيا الألوان في الهوية",
    },
    {
        slug: "booth-staff-training",
        title: "كيف تُجهّز فريق جناحك في المعرض؟",
        seoTitle: "تدريب فريق جناح المعرض: دليل عملي",
        excerpt: "عدد الطاقم المناسب، نص التعريف في 15 ثانية، أسئلة تأهيل الزائر، نظام تسجيل البيانات، وجدول المناوبات — دليل تشغيلي كامل لفريق الجناح.",
        category: "أدلة إرشادية",
        intent: "informational",
        publishAt: "2026-12-02T10:21:00+03:00",
        dateModified: "2026-12-02",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المعارض والفعاليات",
        image: "/images/promotion-counter-table-portable-kiosk.webp",
        imageAlt: "كاونتر ترويجي متنقل داخل جناح معرض في جدة، يمثّل نقطة عمل فريق الاستقبال",
        readTime: "14 دقيقة",
        primaryKeyword: "تدريب فريق جناح المعرض",
    },
];
