/* ⚠️ ملف مولَّد — لا تُعدّله يدوياً.
   المصدر: src/lib/articles/posts/*.ts
   التوليد: node scripts/generate-article-registry.mjs
   يضمّ مقالات 2026-07 فقط — انظر meta.ts للسبب. */

import type { ArticleMeta } from "../meta";

export const META_2026_07: ArticleMeta[] = [
    {
        slug: "prepare-print-file-guide",
        title: "كيف تجهّز ملفك للطباعة بشكل صحيح؟ دليل خطوة بخطوة",
        seoTitle: "دليل تجهيز ملفات الطباعة الصحيح",
        excerpt: "الدليل العملي لتجهيز ملف طباعة خالٍ من الأخطاء: الدقة، الألوان، البليد، الخطوط، وصيغة التصدير النهائية.",
        category: "أدلة إرشادية",
        intent: "informational",
        publishAt: "2026-07-31T17:16:00+03:00",
        dateModified: "2026-07-31",
        author: "فريق بوابة الرواج",
        authorRole: "قسم ما قبل الطباعة",
        image: "/images/print-file-prep-bleed-trim-marks.webp",
        imageAlt: "تجهيز ملف الطباعة على الشاشة مع خطوط الحد الآمن وعلامات القص والـ bleed",
        readTime: "10 دقائق",
        primaryKeyword: "كيف أجهز ملف الطباعة",
    },
    {
        slug: "vehicle-wrapping-price-jeddah",
        title: "أسعار تغليف السيارات في جدة 2026: الفينيل والتكلفة والعمر الافتراضي",
        seoTitle: "أسعار تغليف السيارات في جدة 2026",
        excerpt: "تكلفة تغليف السيارات في جدة حسب نوع الفينيل ومساحة التغطية، وكيف يؤثر مناخ جدة على العمر الافتراضي للتغليف.",
        category: "أسعار",
        intent: "transactional",
        publishAt: "2026-07-29T09:01:00+03:00",
        dateModified: "2026-07-29",
        author: "فريق بوابة الرواج",
        authorRole: "قسم اللافتات والتغليف",
        image: "/images/commercial-vehicle-branding-car-wrapping-jeddah.webp",
        imageAlt: "سيارة تجارية مغلّفة بالفينيل في جدة",
        readTime: "10 دقائق",
        primaryKeyword: "أسعار تغليف السيارات في جدة",
    },
    {
        slug: "exhibition-booth-cost-saudi",
        title: "كم تكلفة تجهيز جناح معرض في السعودية؟ حساب المتر المربع 2026",
        seoTitle: "تكلفة تجهيز جناح معرض في السعودية",
        excerpt: "دليل تكلفة أجنحة المعارض بالمتر المربع: الفرق بين الأوكتانورم والمخصص، ما يشمله السعر، والبنود المخفية التي تفاجئ الشركات.",
        category: "أسعار",
        intent: "transactional",
        publishAt: "2026-07-27T16:21:00+03:00",
        dateModified: "2026-07-27",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المعارض والفعاليات",
        image: "/images/custom-wooden-stand-jeddah-super-dome.webp",
        imageAlt: "جناح معرض خشبي مخصص في جدة سوبر دوم",
        readTime: "12 دقيقة",
        primaryKeyword: "تكلفة تجهيز جناح معرض في السعودية",
    },
    {
        slug: "offset-vs-digital-printing",
        title: "طباعة أوفست أم رقمية؟ الفرق الحقيقي ومتى تختار كلاً منهما",
        seoTitle: "الفرق بين الطباعة الأوفست والرقمية",
        excerpt: "مقارنة عملية بين الطباعة الأوفست والرقمية من حيث التكلفة والجودة والكمية والسرعة، مع نقطة التعادل التي تحدد الخيار الأوفر.",
        category: "مقارنات",
        intent: "informational",
        publishAt: "2026-07-24T16:52:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم الإنتاج",
        image: "/images/printing-machines-digital-offset-equipment.webp",
        imageAlt: "ماكينات الطباعة الرقمية والأوفست في ورشة بجدة",
        readTime: "9 دقائق",
        primaryKeyword: "الفرق بين الطباعة الأوفست والرقمية",
    },
    {
        slug: "roll-up-stand-price-jeddah",
        title: "أسعار رول أب ستاند في جدة 2026: المقاسات والخامات والتكلفة",
        seoTitle: "أسعار رول أب ستاند في جدة 2026",
        excerpt: "دليل كامل لأسعار الرول أب في جدة حسب المقاس ونوع الهيكل وخامة البانر، مع شرح الفرق بين الفئات ومتى تستحق الترقية.",
        category: "أسعار",
        intent: "transactional",
        publishAt: "2026-07-21T11:18:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المعارض والفعاليات",
        image: "/images/roll-up-stand-banner-85x200.webp",
        imageAlt: "رول أب ستاند بمقاس 85×200 سم جاهز للمعرض",
        readTime: "8 دقائق",
        primaryKeyword: "أسعار رول أب ستاند في جدة",
    },
    {
        slug: "shop-signage-municipality-rules-jeddah",
        title: "اشتراطات لوحات المحلات في أمانة جدة: الدليل الكامل 2026",
        seoTitle: "اشتراطات لوحات المحلات في جدة 2026",
        excerpt: "كل ما تحتاج معرفته قبل تركيب لافتة محلك في جدة: الاشتراطات النظامية، نسبة اللغة العربية، المقاسات المسموحة، خطوات التصريح، والمخالفات الشائعة.",
        category: "مرجعي",
        intent: "reference",
        publishAt: "2026-07-17T14:41:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم اللافتات والتركيب",
        image: "/images/jeddah-commercial-street-uniform-shopfronts.webp",
        imageAlt: "شارع تجاري في جدة بواجهات محلات ولوحات موحّدة وفق اشتراطات الأمانة",
        readTime: "11 دقيقة",
        primaryKeyword: "اشتراطات لوحات المحلات في جدة",
    },
    {
        slug: "business-cards-price-jeddah",
        title: "كم سعر طباعة كروت شخصية في جدة؟ دليل الأسعار الكامل 2026",
        seoTitle: "سعر طباعة كروت شخصية في جدة 2026",
        excerpt: "الأسعار الفعلية لطباعة بطاقات العمل في جدة حسب الخامة والكمية والتشطيب، مع جدول مقارنة، وما الذي يجعل السعر يرتفع أو ينخفض.",
        category: "أسعار",
        intent: "transactional",
        publishAt: "2026-07-14T09:34:00+03:00",
        dateModified: "2026-07-26",
        author: "فريق بوابة الرواج",
        authorRole: "قسم المطبوعات التجارية",
        image: "/images/luxury-business-cards-printing-jeddah.webp",
        imageAlt: "بطاقات عمل مطبوعة بتشطيبات مختلفة في جدة",
        readTime: "9 دقائق",
        primaryKeyword: "سعر طباعة كروت شخصية في جدة",
    },
];
